In [12]:
import os 
import fitz 
from docling.document_converter import DocumentConverter 
from langchain_docling import DoclingLoader 
from dotenv import load_dotenv 
from langchain_google_genai import ChatGoogleGenerativeAI
import getpass
from google import genai
from google.genai import types
from langchain_core.messages import AIMessage
from langchain_core.prompts import ChatPromptTemplate

# Content Extraction

In [13]:

path = "/Users/YGT/ygt/RAG-Resume-Analyzer-Agent/documents/data-science-manager-resume-example.pdf"

def extract_text_pdf(filepath): 
    doc = fitz.open(filepath) 
    text = "" 
    for page in doc: 
        text += page.get_text() 
    doc.close() 
    return text.strip()

In [14]:
extract_text_pdf(path)

'KALEB SAXTON\nData Science Manager\nksaxton@email.com\n(123) 456-7890\nHouston, TX\nLinkedIn\nEDUCATION\nB.S.\nMathematics and Economics\nRice University\nSeptember 2008 - April 2012\nHouston, TX\nSKILLS\nPython (NumPy, Pandas, Scikit-\nlearn, Keras, Flask)\nSQL (Redshift, MySQL, Postgres,\nNoSQL)\nGit\nLeadership Experience\nRecommendation Engines\nCustomer Segmentation\nPropensity Modeling\nProductionizing Models\nWORK EXPERIENCE\nData Science Manager\nWestlake Chemical\nFebruary 2018 - current\nHouston, TX\n· Supervised 3 data scientists and 1 data engineer in developing\nmarketing mix models that led to an ROI improvement of 21%\non digital marketing spend over the last 13 months\n· Collaborated with the product and marketing teams to identify\nwhich pre-client interactions increased chances of conversions,\nultimately helping team to increase conversion rates by 32%\n· Developed documentation for methodologies and standards for\nthe growing data science team\n· Identified duplications across team projects, and reduced\ninstances of this by 92% with increased coordination and\naccountability\nSenior Data Scientist\nEnergy Transfer Partners\nJanuary 2015 - February 2018\nHouston, TX\n· Worked closely with the product team to build a production\nprediction engine in Python page, which reduced crude oil profit\nloss by 16%\n· Used random forest models to study well subsets in order to\noptimize and increase efficiency by 22%\n· Compiled and prepared data and reports 2 times per month for\nstakeholders and functional teams\n· Recommended over 100 actionable steps within the first year\nthat improved automation by 7% and profits by 9%\nData Analyst\nCenterPoint Energy\nApril 2012 - January 2015\nHouston, TX\n· Identified process improvements through client data analysis,\nwhich led to a reduced profit loss of 8%\n· Owned the reporting using Python and SQL for energy\nproduction, saving 30+ hours of manual hours each week\n· Built ETL infrastructures and delivered data to Redshift, which\nincreased stakeholder decision making output by 42%\n· Created and developed 5 new testing strategies, and created\nand updated the documentation'

In [15]:
converter = DocumentConverter() 
result = converter.convert(path) 
print(result.document.export_to_markdown())

2025-11-17 19:42:23,956 - INFO - detected formats: [<InputFormat.PDF: 'pdf'>]
2025-11-17 19:42:24,016 - INFO - Going to convert document batch...
2025-11-17 19:42:24,017 - INFO - Initializing pipeline for StandardPdfPipeline with options hash 4f2edc0f7d9bb60b38ebfecf9a2609f5
2025-11-17 19:42:24,039 - INFO - Loading plugin 'docling_defaults'
2025-11-17 19:42:24,040 - WARNING - The plugin langchain_docling will not be loaded because Docling is being executed with allow_external_plugins=false.
2025-11-17 19:42:24,040 - INFO - Registered picture descriptions: ['vlm', 'api']
2025-11-17 19:42:24,049 - INFO - Loading plugin 'docling_defaults'
2025-11-17 19:42:24,052 - WARNING - The plugin langchain_docling will not be loaded because Docling is being executed with allow_external_plugins=false.
2025-11-17 19:42:24,053 - INFO - Registered ocr engines: ['auto', 'easyocr', 'ocrmac', 'rapidocr', 'tesserocr', 'tesseract']
2025-11-17 19:42:25,214 - INFO - Auto OCR model selected ocrmac.
2025-11-17 19:42:25,221 - INFO - Accelerator device: 'mps'
2025-11-17 19:42:29,600 - INFO - Accelerator device: 'mps'
2025-11-17 19:42:30,220 - INFO - Processing document data-science-manager-resume-example.pdf
2025-11-17 19:42:31,542 - INFO - Finished converting document data-science-manager-resume-example.pdf in 7.59 sec.

## KALEB SAXTON

Data Science Manager

- ksaxton@email.com
- (123) 456-7890
- Houston, TX
- LinkedIn

## EDUCATION

B.S.

Mathematics and Economics

## Rice University

- September 2008 - April 2012
- Houston, TX

## SKILLS

Python (NumPy, Pandas, Scikitlearn, Keras, Flask)

SQL (Redshift, MySQL, Postgres, NoSQL)

Git

Leadership Experience

Recommendation Engines

Customer Segmentation

Propensity Modeling

Productionizing Models

## WORK EXPERIENCE

## Data Science Manager

## Westlake Chemical

- February 2018 - current
- Supervised 3 data scientists and 1 data engineer in developing marketing mix models that led to an ROI improvement of 21% on digital marketing spend over the last 13 months
- Collaborated with the product and marketing teams to identify which pre-client interactions increased chances of conversions, ultimately helping team to increase conversion rates by 32%
- Developed documentation for methodologies and standards for the growing data science team
- Identified duplications across team projects, and reduced instances of this by 92% with increased coordination and accountability

- [ ] Houston, TX

## Senior Data Scientist

## Energy Transfer Partners

- January 2015 - February 2018
- Worked closely with the product team to build a production prediction engine in Python page, which reduced crude oil profit loss by 16%
- Used random forest models to study well subsets in order to optimize and increase efficiency by 22%
- Compiled and prepared data and reports 2 times per month for stakeholders and functional teams
- Recommended over 100 actionable steps within the first year that improved automation by 7% and profits by 9%

- Houston, TX

## Data Analyst

## CenterPoint Energy

- April 2012 - January 2015
- Identified process improvements through client data analysis, which led to a reduced profit loss of 8%
- Owned the reporting using Python and SQL for energy production, saving 30+ hours of manual hours each week
- Built ETL infrastructures and delivered data to Redshift, which increased stakeholder decision making output by 42%
- Created and developed 5 new testing strategies, and created and updated the documentation

- Houston, TX

In [16]:
content = result.document.export_to_markdown 
content

<bound method DoclingDocument.export_to_markdown of DoclingDocument(schema_name='DoclingDocument', version='1.7.0', name='data-science-manager-resume-example', origin=DocumentOrigin(mimetype='application/pdf', binary_hash=5637811206403578778, filename='data-science-manager-resume-example.pdf', uri=None), furniture=GroupItem(self_ref='#/furniture', parent=None, children=[], content_layer=<ContentLayer.FURNITURE: 'furniture'>, name='_root_', label=<GroupLabel.UNSPECIFIED: 'unspecified'>), body=GroupItem(self_ref='#/body', parent=None, children=[RefItem(cref='#/texts/0'), RefItem(cref='#/texts/1'), RefItem(cref='#/groups/0'), RefItem(cref='#/texts/6'), RefItem(cref='#/texts/7'), RefItem(cref='#/texts/8'), RefItem(cref='#/texts/9'), RefItem(cref='#/groups/1'), RefItem(cref='#/texts/12'), RefItem(cref='#/texts/13'), RefItem(cref='#/texts/14'), RefItem(cref='#/texts/15'), RefItem(cref='#/texts/16'), RefItem(cref='#/texts/17'), RefItem(cref='#/texts/18'), RefItem(cref='#/texts/19'), RefItem(cref='#/texts/20'), RefItem(cref='#/texts/21'), RefItem(cref='#/texts/22'), RefItem(cref='#/texts/23'), RefItem(cref='#/groups/2'), RefItem(cref='#/groups/3'), RefItem(cref='#/texts/30'), RefItem(cref='#/texts/31'), RefItem(cref='#/groups/4'), RefItem(cref='#/groups/5'), RefItem(cref='#/texts/38'), RefItem(cref='#/texts/39'), RefItem(cref='#/groups/7'), RefItem(cref='#/groups/8')], content_layer=<ContentLayer.BODY: 'body'>, name='_root_', label=<GroupLabel.UNSPECIFIED: 'unspecified'>), groups=[ListGroup(self_ref='#/groups/0', parent=RefItem(cref='#/body'), children=[RefItem(cref='#/texts/2'), RefItem(cref='#/texts/3'), RefItem(cref='#/texts/4'), RefItem(cref='#/texts/5')], content_layer=<ContentLayer.BODY: 'body'>, name='list', label=<GroupLabel.LIST: 'list'>), ListGroup(self_ref='#/groups/1', parent=RefItem(cref='#/body'), children=[RefItem(cref='#/texts/10'), RefItem(cref='#/texts/11')], content_layer=<ContentLayer.BODY: 'body'>, name='list', label=<GroupLabel.LIST: 'list'>), ListGroup(self_ref='#/groups/2', parent=RefItem(cref='#/body'), children=[RefItem(cref='#/texts/24'), RefItem(cref='#/texts/26'), RefItem(cref='#/texts/27'), RefItem(cref='#/texts/28'), RefItem(cref='#/texts/29')], content_layer=<ContentLayer.BODY: 'body'>, name='list', label=<GroupLabel.LIST: 'list'>), GroupItem(self_ref='#/groups/3', parent=RefItem(cref='#/body'), children=[RefItem(cref='#/texts/25')], content_layer=<ContentLayer.BODY: 'body'>, name='group', label=<GroupLabel.FORM_AREA: 'form_area'>), ListGroup(self_ref='#/groups/4', parent=RefItem(cref='#/body'), children=[RefItem(cref='#/texts/32'), RefItem(cref='#/texts/34'), RefItem(cref='#/texts/35'), RefItem(cref='#/texts/36'), RefItem(cref='#/texts/37')], content_layer=<ContentLayer.BODY: 'body'>, name='list', label=<GroupLabel.LIST: 'list'>), GroupItem(self_ref='#/groups/5', parent=RefItem(cref='#/body'), children=[RefItem(cref='#/groups/6')], content_layer=<ContentLayer.BODY: 'body'>, name='group', label=<GroupLabel.FORM_AREA: 'form_area'>), ListGroup(self_ref='#/groups/6', parent=RefItem(cref='#/groups/5'), children=[RefItem(cref='#/texts/33')], content_layer=<ContentLayer.BODY: 'body'>, name='group', label=<GroupLabel.LIST: 'list'>), ListGroup(self_ref='#/groups/7', parent=RefItem(cref='#/body'), children=[RefItem(cref='#/texts/40'), RefItem(cref='#/texts/42'), RefItem(cref='#/texts/43'), RefItem(cref='#/texts/44'), RefItem(cref='#/texts/45')], content_layer=<ContentLayer.BODY: 'body'>, name='list', label=<GroupLabel.LIST: 'list'>), GroupItem(self_ref='#/groups/8', parent=RefItem(cref='#/body'), children=[RefItem(cref='#/groups/9')], content_layer=<ContentLayer.BODY: 'body'>, name='group', label=<GroupLabel.FORM_AREA: 'form_area'>), ListGroup(self_ref='#/groups/9', parent=RefItem(cref='#/groups/8'), children=[RefItem(cref='#/texts/41')], content_layer=<ContentLayer.BODY: 'body'>, name='group', label=<GroupLabel.LIST: 'list'>)], texts=[SectionHeaderItem(self_ref='#/texts/0', parent=RefItem(cref='#/body'), children=[], content_layer=<ContentLayer.BODY: 'body'>, label=<DocItemLabel.SECTION_HEADER: 'section_header'>, prov=[ProvenanceItem(page_no=1, bbox=BoundingBox(l=21.598, t=748.011, r=180.872, b=729.548, coord_origin=<CoordOrigin.BOTTOMLEFT: 'BOTTOMLEFT'>), charspan=(0, 12))], orig='KALEB SAXTON', text='KALEB SAXTON', formatting=None, hyperlink=None, level=1), TextItem(self_ref='#/texts/1', parent=RefItem(cref='#/body'), children=[], content_layer=<ContentLayer.BODY: 'body'>, label=<DocItemLabel.TEXT: 'text'>, prov=[ProvenanceItem(page_no=1, bbox=BoundingBox(l=20.857, t=717.383, r=185.551, b=703.536, coord_origin=<CoordOrigin.BOTTOMLEFT: 'BOTTOMLEFT'>), charspan=(0, 20))], orig='Data Science Manager', text='Data Science Manager', formatting=None, hyperlink=None), ListItem(self_ref='#/texts/2', parent=RefItem(cref='#/groups/0'), children=[], content_layer=<ContentLayer.BODY: 'body'>, label=<DocItemLabel.LIST_ITEM: 'list_item'>, prov=[ProvenanceItem(page_no=1, bbox=BoundingBox(l=41.367, t=677.61, r=150.143, b=667.596, coord_origin=<CoordOrigin.BOTTOMLEFT: 'BOTTOMLEFT'>), charspan=(0, 17))], orig='ksaxton@email.com', text='ksaxton@email.com', formatting=None, hyperlink=None, enumerated=False, marker=''), ListItem(self_ref='#/texts/3', parent=RefItem(cref='#/groups/0'), children=[], content_layer=<ContentLayer.BODY: 'body'>, label=<DocItemLabel.LIST_ITEM: 'list_item'>, prov=[ProvenanceItem(page_no=1, bbox=BoundingBox(l=41.367, t=660.36, r=122.652, b=650.346, coord_origin=<CoordOrigin.BOTTOMLEFT: 'BOTTOMLEFT'>), charspan=(0, 14))], orig='(123) 456-7890', text='456-7890', formatting=None, hyperlink=None, enumerated=True, marker='(123)'), ListItem(self_ref='#/texts/4', parent=RefItem(cref='#/groups/0'), children=[], content_layer=<ContentLayer.BODY: 'body'>, label=<DocItemLabel.LIST_ITEM: 'list_item'>, prov=[ProvenanceItem(page_no=1, bbox=BoundingBox(l=41.367, t=643.11, r=106.716, b=633.096, coord_origin=<CoordOrigin.BOTTOMLEFT: 'BOTTOMLEFT'>), charspan=(0, 11))], orig='Houston, TX', text='Houston, TX', formatting=None, hyperlink=None, enumerated=False, marker=''), ListItem(self_ref='#/texts/5', parent=RefItem(cref='#/groups/0'), children=[], content_layer=<ContentLayer.BODY: 'body'>, label=<DocItemLabel.LIST_ITEM: 'list_item'>, prov=[ProvenanceItem(page_no=1, bbox=BoundingBox(l=41.367, t=625.86, r=88.856, b=615.846, coord_origin=<CoordOrigin.BOTTOMLEFT: 'BOTTOMLEFT'>), charspan=(0, 8))], orig='LinkedIn', text='LinkedIn', formatting=None, hyperlink=None, enumerated=False, marker=''), SectionHeaderItem(self_ref='#/texts/6', parent=RefItem(cref='#/body'), children=[], content_layer=<ContentLayer.BODY: 'body'>, label=<DocItemLabel.SECTION_HEADER: 'section_header'>, prov=[ProvenanceItem(page_no=1, bbox=BoundingBox(l=21.598, t=572.633, r=115.366, b=558.786, coord_origin=<CoordOrigin.BOTTOMLEFT: 'BOTTOMLEFT'>), charspan=(0, 9))], orig='EDUCATION', text='EDUCATION', formatting=None, hyperlink=None, level=1), TextItem(self_ref='#/texts/7', parent=RefItem(cref='#/body'), children=[], content_layer=<ContentLayer.BODY: 'body'>, label=<DocItemLabel.TEXT: 'text'>, prov=[ProvenanceItem(page_no=1, bbox=BoundingBox(l=21.598, t=547.286, r=42.123, b=536.092, coord_origin=<CoordOrigin.BOTTOMLEFT: 'BOTTOMLEFT'>), charspan=(0, 4))], orig='B.S.', text='B.S.', formatting=None, hyperlink=None), TextItem(self_ref='#/texts/8', parent=RefItem(cref='#/body'), children=[], content_layer=<ContentLayer.BODY: 'body'>, label=<DocItemLabel.TEXT: 'text'>, prov=[ProvenanceItem(page_no=1, bbox=BoundingBox(l=21.598, t=528.536, r=184.219, b=517.342, coord_origin=<CoordOrigin.BOTTOMLEFT: 'BOTTOMLEFT'>), charspan=(0, 25))], orig='Mathematics and Economics', text='Mathematics and Economics', formatting=None, hyperlink=None), SectionHeaderItem(self_ref='#/texts/9', parent=RefItem(cref='#/body'), children=[], content_layer=<ContentLayer.BODY: 'body'>, label=<DocItemLabel.SECTION_HEADER: 'section_header'>, prov=[ProvenanceItem(page_no=1, bbox=BoundingBox(l=21.598, t=509.786, r=106.196, b=498.592, coord_origin=<CoordOrigin.BOTTOMLEFT: 'BOTTOMLEFT'>), charspan=(0, 15))], orig='Rice University', text='Rice University', formatting=None, hyperlink=None, level=1), ListItem(self_ref='#/texts/10', parent=RefItem(cref='#/groups/1'), children=[], content_layer=<ContentLayer.BODY: 'body'>, label=<DocItemLabel.LIST_ITEM: 'list_item'>, prov=[ProvenanceItem(page_no=1, bbox=BoundingBox(l=38.367, t=491.61, r=188.662, b=481.596, coord_origin=<CoordOrigin.BOTTOMLEFT: 'BOTTOMLEFT'>), charspan=(0, 27))], orig='September 2008 - April 2012', text='September 2008 - April 2012', formatting=None, hyperlink=None, enumerated=False, marker=''), ListItem(self_ref='#/texts/11', parent=RefItem(cref='#/groups/1'), children=[], content_layer=<ContentLayer.BODY: 'body'>, label=<DocItemLabel.LIST_ITEM: 'list_item'>, prov=[ProvenanceItem(page_no=1, bbox=BoundingBox(l=38.367, t=474.36, r=100.972, b=464.346, coord_origin=<CoordOrigin.BOTTOMLEFT: 'BOTTOMLEFT'>), charspan=(0, 11))], orig='Houston, TX', text='Houston, TX', formatting=None, hyperlink=None, enumerated=False, marker=''), SectionHeaderItem(self_ref='#/texts/12', parent=RefItem(cref='#/body'), children=[], content_layer=<ContentLayer.BODY: 'body'>, label=<DocItemLabel.SECTION_HEADER: 'section_header'>, prov=[ProvenanceItem(page_no=1, bbox=BoundingBox(l=21.598, t=426.383, r=76.645, b=412.536, coord_origin=<CoordOrigin.BOTTOMLEFT: 'BOTTOMLEFT'>), charspan=(0, 6))], orig='SKILLS', text='SKILLS', formatting=None, hyperlink=None, level=1), TextItem(self_ref='#/texts/13', parent=RefItem(cref='#/body'), children=[], content_layer=<ContentLayer.BODY: 'body'>, label=<DocItemLabel.TEXT: 'text'>, prov=[ProvenanceItem(page_no=1, bbox=BoundingBox(l=21.598, t=401.61, r=182.64, b=377.346, coord_origin=<CoordOrigin.BOTTOMLEFT: 'BOTTOMLEFT'>), charspan=(0, 49))], orig='Python (NumPy, Pandas, Scikitlearn, Keras, Flask)', text='Python (NumPy, Pandas, Scikitlearn, Keras, Flask)', formatting=None, hyperlink=None), TextItem(self_ref='#/texts/14', parent=RefItem(cref='#/body'), children=[], content_layer=<ContentLayer.BODY: 'body'>, label=<DocItemLabel.TEXT: 'text'>, prov=[ProvenanceItem(page_no=1, bbox=BoundingBox(l=21.598, t=370.11, r=187.046, b=345.846, coord_origin=<CoordOrigin.BOTTOMLEFT: 'BOTTOMLEFT'>), charspan=(0, 38))], orig='SQL (Redshift, MySQL, Postgres, NoSQL)', text='SQL (Redshift, MySQL, Postgres, NoSQL)', formatting=None, hyperlink=None), TextItem(self_ref='#/texts/15', parent=RefItem(cref='#/body'), children=[], content_layer=<ContentLayer.BODY: 'body'>, label=<DocItemLabel.TEXT: 'text'>, prov=[ProvenanceItem(page_no=1, bbox=BoundingBox(l=21.598, t=338.61, r=36.734, b=328.596, coord_origin=<CoordOrigin.BOTTOMLEFT: 'BOTTOMLEFT'>), charspan=(0, 3))], orig='Git', text='Git', formatting=None, hyperlink=None), TextItem(self_ref='#/texts/16', parent=RefItem(cref='#/body'), children=[], content_layer=<ContentLayer.BODY: 'body'>, label=<DocItemLabel.TEXT: 'text'>, prov=[ProvenanceItem(page_no=1, bbox=BoundingBox(l=21.598, t=321.36, r=138.025, b=311.346, coord_origin=<CoordOrigin.BOTTOMLEFT: 'BOTTOMLEFT'>), charspan=(0, 21))], orig='Leadership Experience', text='Leadership Experience', formatting=None, hyperlink=None), TextItem(self_ref='#/texts/17', parent=RefItem(cref='#/body'), children=[], content_layer=<ContentLayer.BODY: 'body'>, label=<DocItemLabel.TEXT: 'text'>, prov=[ProvenanceItem(page_no=1, bbox=BoundingBox(l=21.598, t=304.11, r=155.85, b=294.096, coord_origin=<CoordOrigin.BOTTOMLEFT: 'BOTTOMLEFT'>), charspan=(0, 22))], orig='Recommendation Engines', text='Recommendation Engines', formatting=None, hyperlink=None), TextItem(self_ref='#/texts/18', parent=RefItem(cref='#/body'), children=[], content_layer=<ContentLayer.BODY: 'body'>, label=<DocItemLabel.TEXT: 'text'>, prov=[ProvenanceItem(page_no=1, bbox=BoundingBox(l=21.598, t=286.86, r=146.105, b=276.846, coord_origin=<CoordOrigin.BOTTOMLEFT: 'BOTTOMLEFT'>), charspan=(0, 21))], orig='Customer Segmentation', text='Customer Segmentation', formatting=None, hyperlink=None), TextItem(self_ref='#/texts/19', parent=RefItem(cref='#/body'), children=[], content_layer=<ContentLayer.BODY: 'body'>, label=<DocItemLabel.TEXT: 'text'>, prov=[ProvenanceItem(page_no=1, bbox=BoundingBox(l=21.598, t=269.61, r=128.879, b=259.596, coord_origin=<CoordOrigin.BOTTOMLEFT: 'BOTTOMLEFT'>), charspan=(0, 19))], orig='Propensity Modeling', text='Propensity Modeling', formatting=None, hyperlink=None), TextItem(self_ref='#/texts/20', parent=RefItem(cref='#/body'), children=[], content_layer=<ContentLayer.BODY: 'body'>, label=<DocItemLabel.TEXT: 'text'>, prov=[ProvenanceItem(page_no=1, bbox=BoundingBox(l=21.598, t=252.36, r=143.85, b=242.346, coord_origin=<CoordOrigin.BOTTOMLEFT: 'BOTTOMLEFT'>), charspan=(0, 22))], orig='Productionizing Models', text='Productionizing Models', formatting=None, hyperlink=None), SectionHeaderItem(self_ref='#/texts/21', parent=RefItem(cref='#/body'), children=[], content_layer=<ContentLayer.BODY: 'body'>, label=<DocItemLabel.SECTION_HEADER: 'section_header'>, prov=[ProvenanceItem(page_no=1, bbox=BoundingBox(l=230.402, t=749.633, r=381.854, b=735.786, coord_origin=<CoordOrigin.BOTTOMLEFT: 'BOTTOMLEFT'>), charspan=(0, 15))], orig='WORK EXPERIENCE', text='WORK EXPERIENCE', formatting=None, hyperlink=None, level=1), SectionHeaderItem(self_ref='#/texts/22', parent=RefItem(cref='#/body'), children=[], content_layer=<ContentLayer.BODY: 'body'>, label=<DocItemLabel.SECTION_HEADER: 'section_header'>, prov=[ProvenanceItem(page_no=1, bbox=BoundingBox(l=230.402, t=723.599, r=394.249, b=709.458, coord_origin=<CoordOrigin.BOTTOMLEFT: 'BOTTOMLEFT'>), charspan=(0, 20))], orig='Data Science Manager', text='Data Science Manager', formatting=None, hyperlink=None, level=1), SectionHeaderItem(self_ref='#/texts/23', parent=RefItem(cref='#/body'), children=[], content_layer=<ContentLayer.BODY: 'body'>, label=<DocItemLabel.SECTION_HEADER: 'section_header'>, prov=[ProvenanceItem(page_no=1, bbox=BoundingBox(l=230.402, t=701.786, r=337.334, b=690.592, coord_origin=<CoordOrigin.BOTTOMLEFT: 'BOTTOMLEFT'>), charspan=(0, 17))], orig='Westlake Chemical', text='Westlake Chemical', formatting=None, hyperlink=None, level=1), ListItem(self_ref='#/texts/24', parent=RefItem(cref='#/groups/2'), children=[], content_layer=<ContentLayer.BODY: 'body'>, label=<DocItemLabel.LIST_ITEM: 'list_item'>, prov=[ProvenanceItem(page_no=1, bbox=BoundingBox(l=247.172, t=683.61, r=371.059, b=673.596, coord_origin=<CoordOrigin.BOTTOMLEFT: 'BOTTOMLEFT'>), charspan=(0, 23))], orig='February 2018 - current', text='February 2018 - current', formatting=None, hyperlink=None, enumerated=False, marker=''), TextItem(self_ref='#/texts/25', parent=RefItem(cref='#/groups/3'), children=[], content_layer=<ContentLayer.BODY: 'body'>, label=<DocItemLabel.CHECKBOX_UNSELECTED: 'checkbox_unselected'>, prov=[ProvenanceItem(page_no=1, bbox=BoundingBox(l=423.691, t=683.61, r=486.296, b=673.596, coord_origin=<CoordOrigin.BOTTOMLEFT: 'BOTTOMLEFT'>), charspan=(0, 11))], orig='Houston, TX', text='Houston, TX', formatting=None, hyperlink=None), ListItem(self_ref='#/texts/26', parent=RefItem(cref='#/groups/2'), children=[], content_layer=<ContentLayer.BODY: 'body'>, label=<DocItemLabel.LIST_ITEM: 'list_item'>, prov=[ProvenanceItem(page_no=1, bbox=BoundingBox(l=245.402, t=668.885, r=579.966, b=627.846, coord_origin=<CoordOrigin.BOTTOMLEFT: 'BOTTOMLEFT'>), charspan=(0, 174))], orig='· Supervised 3 data scientists and 1 data engineer in developing marketing mix models that led to an ROI improvement of 21% on digital marketing spend over the last 13 months', text='Supervised 3 data scientists and 1 data engineer in developing marketing mix models that led to an ROI improvement of 21% on digital marketing spend over the last 13 months', formatting=None, hyperlink=None, enumerated=False, marker='·'), ListItem(self_ref='#/texts/27', parent=RefItem(cref='#/groups/2'), children=[], content_layer=<ContentLayer.BODY: 'body'>, label=<DocItemLabel.LIST_ITEM: 'list_item'>, prov=[ProvenanceItem(page_no=1, bbox=BoundingBox(l=245.402, t=623.135, r=582.601, b=582.096, coord_origin=<CoordOrigin.BOTTOMLEFT: 'BOTTOMLEFT'>), charspan=(0, 187))], orig='· Collaborated with the product and marketing teams to identify which pre-client interactions increased chances of conversions, ultimately helping team to increase conversion rates by 32%', text='Collaborated with the product and marketing teams to identify which pre-client interactions increased chances of conversions, ultimately helping team to increase conversion rates by 32%', formatting=None, hyperlink=None, enumerated=False, marker='·'), ListItem(self_ref='#/texts/28', parent=RefItem(cref='#/groups/2'), children=[], content_layer=<ContentLayer.BODY: 'body'>, label=<DocItemLabel.LIST_ITEM: 'list_item'>, prov=[ProvenanceItem(page_no=1, bbox=BoundingBox(l=245.402, t=577.385, r=588.147, b=550.596, coord_origin=<CoordOrigin.BOTTOMLEFT: 'BOTTOMLEFT'>), charspan=(0, 91))], orig='· Developed documentation for methodologies and standards for the growing data science team', text='Developed documentation for methodologies and standards for the growing data science team', formatting=None, hyperlink=None, enumerated=False, marker='·'), ListItem(self_ref='#/texts/29', parent=RefItem(cref='#/groups/2'), children=[], content_layer=<ContentLayer.BODY: 'body'>, label=<DocItemLabel.LIST_ITEM: 'list_item'>, prov=[ProvenanceItem(page_no=1, bbox=BoundingBox(l=245.402, t=545.885, r=552.899, b=504.846, coord_origin=<CoordOrigin.BOTTOMLEFT: 'BOTTOMLEFT'>), charspan=(0, 131))], orig='· Identified duplications across team projects, and reduced instances of this by 92% with increased coordination and accountability', text='Identified duplications across team projects, and reduced instances of this by 92% with increased coordination and accountability', formatting=None, hyperlink=None, enumerated=False, marker='·'), SectionHeaderItem(self_ref='#/texts/30', parent=RefItem(cref='#/body'), children=[], content_layer=<ContentLayer.BODY: 'body'>, label=<DocItemLabel.SECTION_HEADER: 'section_header'>, prov=[ProvenanceItem(page_no=1, bbox=BoundingBox(l=230.402, t=478.349, r=381.391, b=464.208, coord_origin=<CoordOrigin.BOTTOMLEFT: 'BOTTOMLEFT'>), charspan=(0, 21))], orig='Senior Data Scientist', text='Senior Data Scientist', formatting=None, hyperlink=None, level=1), SectionHeaderItem(self_ref='#/texts/31', parent=RefItem(cref='#/body'), children=[], content_layer=<ContentLayer.BODY: 'body'>, label=<DocItemLabel.SECTION_HEADER: 'section_header'>, prov=[ProvenanceItem(page_no=1, bbox=BoundingBox(l=230.402, t=456.536, r=374.394, b=445.342, coord_origin=<CoordOrigin.BOTTOMLEFT: 'BOTTOMLEFT'>), charspan=(0, 24))], orig='Energy Transfer Partners', text='Energy Transfer Partners', formatting=None, hyperlink=None, level=1), ListItem(self_ref='#/texts/32', parent=RefItem(cref='#/groups/4'), children=[], content_layer=<ContentLayer.BODY: 'body'>, label=<DocItemLabel.LIST_ITEM: 'list_item'>, prov=[ProvenanceItem(page_no=1, bbox=BoundingBox(l=247.172, t=438.36, r=401.967, b=428.346, coord_origin=<CoordOrigin.BOTTOMLEFT: 'BOTTOMLEFT'>), charspan=(0, 28))], orig='January 2015 - February 2018', text='January 2015 - February 2018', formatting=None, hyperlink=None, enumerated=False, marker=''), ListItem(self_ref='#/texts/33', parent=RefItem(cref='#/groups/6'), children=[], content_layer=<ContentLayer.BODY: 'body'>, label=<DocItemLabel.LIST_ITEM: 'list_item'>, prov=[ProvenanceItem(page_no=1, bbox=BoundingBox(l=455.191, t=438.36, r=517.796, b=428.346, coord_origin=<CoordOrigin.BOTTOMLEFT: 'BOTTOMLEFT'>), charspan=(0, 11))], orig='Houston, TX', text='Houston, TX', formatting=None, hyperlink=None, enumerated=False, marker=''), ListItem(self_ref='#/texts/34', parent=RefItem(cref='#/groups/4'), children=[], content_layer=<ContentLayer.BODY: 'body'>, label=<DocItemLabel.LIST_ITEM: 'list_item'>, prov=[ProvenanceItem(page_no=1, bbox=BoundingBox(l=245.402, t=423.635, r=589.789, b=382.596, coord_ori

# Document Parsing

In [17]:
loader = DoclingLoader(path) 
docs = loader.load()

2025-11-17 19:42:32,442 - INFO - detected formats: [<InputFormat.PDF: 'pdf'>]
2025-11-17 19:42:32,444 - INFO - Going to convert document batch...
2025-11-17 19:42:32,445 - INFO - Initializing pipeline for StandardPdfPipeline with options hash 4f2edc0f7d9bb60b38ebfecf9a2609f5
2025-11-17 19:42:32,447 - INFO - Auto OCR model selected ocrmac.
2025-11-17 19:42:32,448 - INFO - Accelerator device: 'mps'
2025-11-17 19:42:33,934 - INFO - Accelerator device: 'mps'
2025-11-17 19:42:34,255 - INFO - Processing document data-science-manager-resume-example.pdf
2025-11-17 19:42:34,940 - INFO - Finished converting document data-science-manager-resume-example.pdf in 2.50 sec.

In [18]:
for d in docs[:3]: 
    print(f"- {d.page_content=}")

- d.page_content='KALEB SAXTON\nData Science Manager\n- ksaxton@email.com\n- (123) 456-7890\n- Houston, TX\n- LinkedIn'
- d.page_content='EDUCATION\nB.S.\nMathematics and Economics'
- d.page_content='Rice University\n- September 2008 - April 2012\n- Houston, TX'

# Loading LLM

In [117]:
load_dotenv()

True

In [118]:

GOOGLE_API_KEY= os.getenv("GOOGLE_API_KEY")

In [119]:
def load_llm(id_model: str, temperature: float): 
    llm = ChatGoogleGenerativeAI(
        model="gemini-2.5-flash",
        temperature=temperature,
        max_tokens=None,
        timeout=None,
        max_retries=2
    )
    
    return llm

In [ ]:
from langchain_ollama import ChatOllama

def load_local_llm(): 
    llm = ChatOllama( 
        model="llama3", 
        temperature=0
    ) 

    return llm

In [136]:
llm = load_local_llm()

In [ ]:
prompt = f"""
2+2 ? 
{content}
"""
output = llm.invoke(prompt) 
output

2025-11-18 15:50:13,187 - INFO - HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

AIMessage(content='2+2 is 4.', additional_kwargs={}, response_metadata={'model': 'llama3', 'created_at': '2025-11-18T12:50:14.135601Z', 'done': True, 'done_reason': 'stop', 'total_duration': 58098624667, 'load_duration': 112578458, 'prompt_eval_count': 4096, 'prompt_eval_duration': 56944611709, 'eval_count': 8, 'eval_duration': 872708167, 'model_name': 'llama3', 'model_provider': 'ollama'}, id='lc_run--8ce94dbb-bd72-4647-a855-763a7e8b3a4b-0', usage_metadata={'input_tokens': 4096, 'output_tokens': 8, 'total_tokens': 4104})

In [120]:
llm = load_llm(id_model="gemini-2.5-flash", temperature=0)

In [ ]:
llm = load_local_llm

## Test LLM

In [121]:
prompt = f"""
Summarize this resume just in 1 paragraph: 
{content}
"""

print(prompt)

Summarize this resume just in 1 paragraph:

In [ ]:
output = llm.invoke(prompt) 
res = output.content

KeyboardInterrupt:

## Displaying the Result

In [25]:
def show_result(result): 
    from IPython.display import Markdown 
    display(Markdown(result)) 

show_result(res)

Kaleb Saxton is an experienced Data Science Manager with a B.S. in Mathematics and Economics from Rice University, demonstrating a strong track record of leading data science initiatives and driving significant business improvements. Currently at Westlake Chemical, Kaleb supervises a team of data scientists and engineers, having achieved a 21% ROI improvement on digital marketing spend through marketing mix models and a 32% increase in conversion rates by optimizing pre-client interactions. Previously, as a Senior Data Scientist at Energy Transfer Partners, Kaleb reduced crude oil profit loss by 16% with a Python prediction engine and optimized efficiency by 22% using random forest models, also recommending actionable steps that improved automation by 7% and profits by 9%. As a Data Analyst at CenterPoint Energy, Kaleb identified process improvements that reduced profit loss by 8%, automated reporting saving 30+ manual hours weekly, and built ETL infrastructures that increased stakeholder decision-making output by 42%. Kaleb's technical proficiencies include Python (NumPy, Pandas, Scikitlearn, Keras, Flask), SQL (Redshift, MySQL, Postgres, NoSQL), Git, and expertise in recommendation engines, customer segmentation, propensity modeling, and productionizing models.

# Building the Prompt

## Prompt Base

In [26]:
from langchain_core.prompts import ( 
    ChatPromptTemplate, 
    HumanMessagePromptTemplate, 
    MessagesPlaceholder
) 

prompt_template = ChatPromptTemplate.from_template(
"""
You are a Human Resources specialist with extensive experience in resume analysis. 
Your task is to review the content below and extract the information using the exact JSON structure provided.
Respond with only the structured JSON output and use only the specified keys. 
Make sure the key names match the schema exactly. 
Do not include explanations or comments outside the JSON.

Schema:
{schema}
                                                   
--- 

Resume to be analyzed: 
'{resume}'                                         
""")

In [27]:
prompt_template

ChatPromptTemplate(input_variables=['resume', 'schema'], input_types={}, partial_variables={}, messages=[HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['resume', 'schema'], input_types={}, partial_variables={}, template="\nYou are a Human Resources specialist with extensive experience in resume analysis. \nYour task is to review the content below and extract the information using the exact JSON structure provided.\nRespond with only the structured JSON output and use only the specified keys. \nMake sure the key names match the schema exactly. \nDo not include explanations or comments outside the JSON.\n\nSchema:\n{schema}\n\n--- \n\nResume to be analyzed: \n'{resume}'                                         \n"), additional_kwargs={})])

### Defining Schema for Resume Parsing

- Full Name 
- Area of Expertise 
- Profile Summary 
- Projects and Achivements Summary
- Key Skills 
- Education 
- Suggested Interview Question

In [28]:
schema = """
{ 
    "name": "Full name of the candidate", 
    "area": "Primary area of field", 
    "summary": "Concise summary of the candidate",
    "projects": [
        {"project_title": "string", "achievements_summary": "string"},
        {"project_title": "string", "achievements_summary": "string"}
    ],
    "skills": ["skill 1", "skill 2", "..."],
    "education": "Summary of the most relevant academic background", 
    "interview_questions": "Useful interview question based on the resume, to clarify or explore a specific point",
}
"""

In [29]:
chain = prompt_template | llm 
output = chain.invoke({"schema": schema, "resume": content}) 

show_result(output.content)

```json
{
    "name": "KALEB SAXTON",
    "area": "Data Science Manager",
    "summary": "Highly experienced Data Science Manager with a strong background in leading data science and engineering teams, developing advanced predictive models, and driving significant business improvements. Proven ability to enhance ROI, increase conversion rates, optimize efficiency, and reduce profit loss through strategic data analysis and model productionization.",
    "projects": [
        {
            "project_title": "Data Science Manager at Westlake Chemical",
            "achievements_summary": "Supervised a team of 3 data scientists and 1 data engineer in developing marketing mix models, leading to a 21% ROI improvement on digital marketing spend. Collaborated with product and marketing teams to identify pre-client interactions, increasing conversion rates by 32%. Developed documentation for data science methodologies and standards, and reduced project duplications by 92% through improved coordination."
        },
        {
            "project_title": "Senior Data Scientist at Energy Transfer Partners",
            "achievements_summary": "Worked closely with the product team to build a production prediction engine in Python, which reduced crude oil profit loss by 16%. Utilized random forest models to study well subsets, optimizing and increasing efficiency by 22%. Compiled and prepared data and reports for stakeholders and functional teams, and recommended over 100 actionable steps that improved automation by 7% and profits by 9% within the first year."
        },
        {
            "project_title": "Data Analyst at CenterPoint Energy",
            "achievements_summary": "Identified process improvements through client data analysis, leading to an 8% reduction in profit loss. Owned reporting using Python and SQL for energy production, saving 30+ hours of manual work each week. Built ETL infrastructures and delivered data to Redshift, increasing stakeholder decision-making output by 42%. Created and developed 5 new testing strategies and updated documentation."
        }
    ],
    "skills": [
        "Python (NumPy, Pandas, Scikitlearn, Keras, Flask)",
        "SQL (Redshift, MySQL, Postgres, NoSQL)",
        "Git",
        "Leadership Experience",
        "Recommendation Engines",
        "Customer Segmentation",
        "Propensity Modeling",
        "Productionizing Models"
    ],
    "education": "B.S. in Mathematics and Economics from Rice University, Houston, TX (September 2008 - April 2012).",
    "interview_questions": "You've demonstrated significant impact in reducing project duplications by 92% and improving automation by 7%. Can you elaborate on your methodology for identifying these inefficiencies and the specific strategies you employed to achieve such substantial improvements?"
}
```

### Wrapping It All in a Function

In [30]:
import json 
import re 
def format_result(result):
    cleaned_string = result.strip()
    
    if cleaned_string.startswith("'") and cleaned_string.endswith("'"):
        cleaned_string = cleaned_string[1:-1].strip()
    
    match = re.search(r'\{.*\}', cleaned_string, re.DOTALL)
    
    if match:
        final_json_string = match.group(0)
    else:
        final_json_string = cleaned_string

    return json.loads(final_json_string)

In [31]:
def process_resume(schema, content): 
    chain = prompt_template | llm 
    output = chain.invoke({"schema": schema, "resume": content})
    result = format_result(output.content)
    return output, result

In [32]:
output, result = process_resume(schema, content)

In [33]:
output

AIMessage(content='```json\n{\n    "name": "KALEB SAXTON",\n    "area": "Data Science Management",\n    "summary": "Highly accomplished Data Science Manager with extensive experience in leading data science teams, developing predictive models, and driving significant business improvements. Proven track record in marketing mix modeling, conversion rate optimization, profit loss reduction, and enhancing operational efficiency through data-driven strategies and robust ETL infrastructure.",\n    "projects": [\n        {\n            "project_title": "Marketing Mix Model Development (Westlake Chemical)",\n            "achievements_summary": "Supervised 3 data scientists and 1 data engineer in developing marketing mix models, leading to a 21% ROI improvement on digital marketing spend over 13 months."\n        },\n        {\n            "project_title": "Client Conversion Rate Optimization (Westlake Chemical)",\n            "achievements_summary": "Collaborated with product and marketing teams to identify pre-client interactions increasing conversions, ultimately boosting conversion rates by 32%."\n        },\n        {\n            "project_title": "Data Science Methodologies and Standards (Westlake Chemical)",\n            "achievements_summary": "Developed comprehensive documentation for methodologies and standards for the growing data science team."\n        },\n        {\n            "project_title": "Project Duplication Reduction (Westlake Chemical)",\n            "achievements_summary": "Identified and reduced duplications across team projects by 92% through increased coordination and accountability."\n        },\n        {\n            "project_title": "Production Prediction Engine (Energy Transfer Partners)",\n            "achievements_summary": "Worked closely with the product team to build a production prediction engine in Python, reducing crude oil profit loss by 16%."\n        },\n        {\n            "project_title": "Well Subset Optimization (Energy Transfer Partners)",\n            "achievements_summary": "Used random forest models to study well subsets, optimizing and increasing efficiency by 22%."\n        },\n        {\n            "project_title": "Automation and Profit Improvement (Energy Transfer Partners)",\n            "achievements_summary": "Recommended over 100 actionable steps within the first year, improving automation by 7% and profits by 9%."\n        },\n        {\n            "project_title": "Process Improvement through Data Analysis (CenterPoint Energy)",\n            "achievements_summary": "Identified process improvements through client data analysis, leading to an 8% reduction in profit loss."\n        },\n        {\n            "project_title": "Energy Production Reporting (CenterPoint Energy)",\n            "achievements_summary": "Owned reporting using Python and SQL for energy production, saving 30+ hours of manual work each week."\n        },\n        {\n            "project_title": "ETL Infrastructure Development (CenterPoint Energy)",\n            "achievements_summary": "Built ETL infrastructures and delivered data to Redshift, increasing stakeholder decision-making output by 42%."\n        },\n        {\n            "project_title": "Testing Strategies Development (CenterPoint Energy)",\n            "achievements_summary": "Created and developed 5 new testing strategies, along with creating and updating their documentation."\n        }\n    ],\n    "skills": [\n        "Python (NumPy, Pandas, Scikitlearn, Keras, Flask)",\n        "SQL (Redshift, MySQL, Postgres, NoSQL)",\n        "Git",\n        "Leadership Experience",\n        "Recommendation Engines",\n        "Customer Segmentation",\n        "Propensity Modeling",\n        "Productionizing Models",\n        "Marketing Mix Models",\n        "Random Forest Models",\n        "ETL Infrastructure",\n        "Data Analysis",\n        "Reporting"\n    ],\n    "education": "B.S. in Mathematics and Economics from Rice University, Houston, TX (September 2008 - April 2012).",\n    "interview_questions": "Regarding your achievement at Westlake Chemical where you supervised the development of marketing mix models leading to a 21% ROI improvement, could you describe the most significant challenge your team faced during this project and how you navigated it?"\n}\n```', additional_kwargs={}, response_metadata={'prompt_feedback': {'block_reason': 0, 'safety_ratings': []}, 'finish_reason': 'STOP', 'model_name': 'gemini-2.5-flash', 'safety_ratings': [], 'grounding_metadata': {}, 'model_provider': 'google_genai'}, id='lc_run--0efb1c40-b50c-47aa-ad15-97dcb4cc92c6-0', usage_metadata={'input_tokens': 9554, 'output_tokens': 2468, 'total_tokens': 12022, 'input_token_details': {'cache_read': 0}, 'output_token_details': {'reasoning': 1566}})

In [34]:
result

{'name': 'KALEB SAXTON',
 'area': 'Data Science Management',
 'summary': 'Highly accomplished Data Science Manager with extensive experience in leading data science teams, developing predictive models, and driving significant business improvements. Proven track record in marketing mix modeling, conversion rate optimization, profit loss reduction, and enhancing operational efficiency through data-driven strategies and robust ETL infrastructure.',
 'projects': [{'project_title': 'Marketing Mix Model Development (Westlake Chemical)',
   'achievements_summary': 'Supervised 3 data scientists and 1 data engineer in developing marketing mix models, leading to a 21% ROI improvement on digital marketing spend over 13 months.'},
  {'project_title': 'Client Conversion Rate Optimization (Westlake Chemical)',
   'achievements_summary': 'Collaborated with product and marketing teams to identify pre-client interactions increasing conversions, ultimately boosting conversion rates by 32%.'},
  {'project_title': 'Data Science Methodologies and Standards (Westlake Chemical)',
   'achievements_summary': 'Developed comprehensive documentation for methodologies and standards for the growing data science team.'},
  {'project_title': 'Project Duplication Reduction (Westlake Chemical)',
   'achievements_summary': 'Identified and reduced duplications across team projects by 92% through increased coordination and accountability.'},
  {'project_title': 'Production Prediction Engine (Energy Transfer Partners)',
   'achievements_summary': 'Worked closely with the product team to build a production prediction engine in Python, reducing crude oil profit loss by 16%.'},
  {'project_title': 'Well Subset Optimization (Energy Transfer Partners)',
   'achievements_summary': 'Used random forest models to study well subsets, optimizing and increasing efficiency by 22%.'},
  {'project_title': 'Automation and Profit Improvement (Energy Transfer Partners)',
   'achievements_summary': 'Recommended over 100 actionable steps within the first year, improving automation by 7% and profits by 9%.'},
  {'project_title': 'Process Improvement through Data Analysis (CenterPoint Energy)',
   'achievements_summary': 'Identified process improvements through client data analysis, leading to an 8% reduction in profit loss.'},
  {'project_title': 'Energy Production Reporting (CenterPoint Energy)',
   'achievements_summary': 'Owned reporting using Python and SQL for energy production, saving 30+ hours of manual work each week.'},
  {'project_title': 'ETL Infrastructure Development (CenterPoint Energy)',
   'achievements_summary': 'Built ETL infrastructures and delivered data to Redshift, increasing stakeholder decision-making output by 42%.'},
  {'project_title': 'Testing Strategies Development (CenterPoint Energy)',
   'achievements_summary': 'Created and developed 5 new testing strategies, along with creating and updating their documentation.'}],
 'skills': ['Python (NumPy, Pandas, Scikitlearn, Keras, Flask)',
  'SQL (Redshift, MySQL, Postgres, NoSQL)',
  'Git',
  'Leadership Experience',
  'Recommendation Engines',
  'Customer Segmentation',
  'Propensity Modeling',
  'Productionizing Models',
  'Marketing Mix Models',
  'Random Forest Models',
  'ETL Infrastructure',
  'Data Analysis',
  'Reporting'],
 'education': 'B.S. in Mathematics and Economics from Rice University, Houston, TX (September 2008 - April 2012).',
 'interview_questions': 'Regarding your achievement at Westlake Chemical where you supervised the development of marketing mix models leading to a 21% ROI improvement, could you describe the most significant challenge your team faced during this project and how you navigated it?'}

### Validating the Output

In [35]:
def parse_result_llm(response: AIMessage, required_fields: list) -> dict: 

    response_text = response.content 

    if "</think>" in response_text:
        response_text = response_text.split("</think>")[-1].strip()

    start_idx = response_text.find('{') 
    end_idx = response_text.rfind('}') + 1 

    if start_idx == -1 or end_idx == 0 or start_idx >= end_idx: 
        print("error")
        return {"error": "No json found in response"}
        
    json_str = response_text[start_idx:end_idx].strip()
    
    info_resume = json.loads(json_str) 

    for field in required_fields: 
        if field not in info_resume or info_resume[field] is None: 
            info_resume[field] = [] 
            
    return info_resume

In [36]:
fields = ["name",
    "area",
    "summary",
    "projects",
    "skills",
    "education",
    "interview_questions"]

In [37]:
structured_data = parse_result_llm(output, fields)

In [38]:
structured_data

{'name': 'KALEB SAXTON',
 'area': 'Data Science Management',
 'summary': 'Highly accomplished Data Science Manager with extensive experience in leading data science teams, developing predictive models, and driving significant business improvements. Proven track record in marketing mix modeling, conversion rate optimization, profit loss reduction, and enhancing operational efficiency through data-driven strategies and robust ETL infrastructure.',
 'projects': [{'project_title': 'Marketing Mix Model Development (Westlake Chemical)',
   'achievements_summary': 'Supervised 3 data scientists and 1 data engineer in developing marketing mix models, leading to a 21% ROI improvement on digital marketing spend over 13 months.'},
  {'project_title': 'Client Conversion Rate Optimization (Westlake Chemical)',
   'achievements_summary': 'Collaborated with product and marketing teams to identify pre-client interactions increasing conversions, ultimately boosting conversion rates by 32%.'},
  {'project_title': 'Data Science Methodologies and Standards (Westlake Chemical)',
   'achievements_summary': 'Developed comprehensive documentation for methodologies and standards for the growing data science team.'},
  {'project_title': 'Project Duplication Reduction (Westlake Chemical)',
   'achievements_summary': 'Identified and reduced duplications across team projects by 92% through increased coordination and accountability.'},
  {'project_title': 'Production Prediction Engine (Energy Transfer Partners)',
   'achievements_summary': 'Worked closely with the product team to build a production prediction engine in Python, reducing crude oil profit loss by 16%.'},
  {'project_title': 'Well Subset Optimization (Energy Transfer Partners)',
   'achievements_summary': 'Used random forest models to study well subsets, optimizing and increasing efficiency by 22%.'},
  {'project_title': 'Automation and Profit Improvement (Energy Transfer Partners)',
   'achievements_summary': 'Recommended over 100 actionable steps within the first year, improving automation by 7% and profits by 9%.'},
  {'project_title': 'Process Improvement through Data Analysis (CenterPoint Energy)',
   'achievements_summary': 'Identified process improvements through client data analysis, leading to an 8% reduction in profit loss.'},
  {'project_title': 'Energy Production Reporting (CenterPoint Energy)',
   'achievements_summary': 'Owned reporting using Python and SQL for energy production, saving 30+ hours of manual work each week.'},
  {'project_title': 'ETL Infrastructure Development (CenterPoint Energy)',
   'achievements_summary': 'Built ETL infrastructures and delivered data to Redshift, increasing stakeholder decision-making output by 42%.'},
  {'project_title': 'Testing Strategies Development (CenterPoint Energy)',
   'achievements_summary': 'Created and developed 5 new testing strategies, along with creating and updating their documentation.'}],
 'skills': ['Python (NumPy, Pandas, Scikitlearn, Keras, Flask)',
  'SQL (Redshift, MySQL, Postgres, NoSQL)',
  'Git',
  'Leadership Experience',
  'Recommendation Engines',
  'Customer Segmentation',
  'Propensity Modeling',
  'Productionizing Models',
  'Marketing Mix Models',
  'Random Forest Models',
  'ETL Infrastructure',
  'Data Analysis',
  'Reporting'],
 'education': 'B.S. in Mathematics and Economics from Rice University, Houston, TX (September 2008 - April 2012).',
 'interview_questions': 'Regarding your achievement at Westlake Chemical where you supervised the development of marketing mix models leading to a 21% ROI improvement, could you describe the most significant challenge your team faced during this project and how you navigated it?'}

### Saving and Loading Structured Data

In [39]:
path_json = "/Users/YGT/ygt/RAG-Resume-Analyzer-Agent/result/resumes.json" 

def save_json_resume(result, path_json): 
    with open(path_json, "w", encoding="utf-8") as f: 
        json.dump(result, f, indent=2, ensure_ascii=False) 

save_json_resume(structured_data, path_json)

### Loading the Json file contents

In [40]:
def load_json_resume(path_json): 
    with open(path_json, "r", encoding="utf-8") as f: 
        return json.load(f) 
    
result_resume = load_json_resume(path_json) 
result_resume

{'name': 'KALEB SAXTON',
 'area': 'Data Science Management',
 'summary': 'Highly accomplished Data Science Manager with extensive experience in leading data science teams, developing predictive models, and driving significant business improvements. Proven track record in marketing mix modeling, conversion rate optimization, profit loss reduction, and enhancing operational efficiency through data-driven strategies and robust ETL infrastructure.',
 'projects': [{'project_title': 'Marketing Mix Model Development (Westlake Chemical)',
   'achievements_summary': 'Supervised 3 data scientists and 1 data engineer in developing marketing mix models, leading to a 21% ROI improvement on digital marketing spend over 13 months.'},
  {'project_title': 'Client Conversion Rate Optimization (Westlake Chemical)',
   'achievements_summary': 'Collaborated with product and marketing teams to identify pre-client interactions increasing conversions, ultimately boosting conversion rates by 32%.'},
  {'project_title': 'Data Science Methodologies and Standards (Westlake Chemical)',
   'achievements_summary': 'Developed comprehensive documentation for methodologies and standards for the growing data science team.'},
  {'project_title': 'Project Duplication Reduction (Westlake Chemical)',
   'achievements_summary': 'Identified and reduced duplications across team projects by 92% through increased coordination and accountability.'},
  {'project_title': 'Production Prediction Engine (Energy Transfer Partners)',
   'achievements_summary': 'Worked closely with the product team to build a production prediction engine in Python, reducing crude oil profit loss by 16%.'},
  {'project_title': 'Well Subset Optimization (Energy Transfer Partners)',
   'achievements_summary': 'Used random forest models to study well subsets, optimizing and increasing efficiency by 22%.'},
  {'project_title': 'Automation and Profit Improvement (Energy Transfer Partners)',
   'achievements_summary': 'Recommended over 100 actionable steps within the first year, improving automation by 7% and profits by 9%.'},
  {'project_title': 'Process Improvement through Data Analysis (CenterPoint Energy)',
   'achievements_summary': 'Identified process improvements through client data analysis, leading to an 8% reduction in profit loss.'},
  {'project_title': 'Energy Production Reporting (CenterPoint Energy)',
   'achievements_summary': 'Owned reporting using Python and SQL for energy production, saving 30+ hours of manual work each week.'},
  {'project_title': 'ETL Infrastructure Development (CenterPoint Energy)',
   'achievements_summary': 'Built ETL infrastructures and delivered data to Redshift, increasing stakeholder decision-making output by 42%.'},
  {'project_title': 'Testing Strategies Development (CenterPoint Energy)',
   'achievements_summary': 'Created and developed 5 new testing strategies, along with creating and updating their documentation.'}],
 'skills': ['Python (NumPy, Pandas, Scikitlearn, Keras, Flask)',
  'SQL (Redshift, MySQL, Postgres, NoSQL)',
  'Git',
  'Leadership Experience',
  'Recommendation Engines',
  'Customer Segmentation',
  'Propensity Modeling',
  'Productionizing Models',
  'Marketing Mix Models',
  'Random Forest Models',
  'ETL Infrastructure',
  'Data Analysis',
  'Reporting'],
 'education': 'B.S. in Mathematics and Economics from Rice University, Houston, TX (September 2008 - April 2012).',
 'interview_questions': 'Regarding your achievement at Westlake Chemical where you supervised the development of marketing mix models leading to a 21% ROI improvement, could you describe the most significant challenge your team faced during this project and how you navigated it?'}

In [41]:
for key in result_resume.keys(): 
    print(key)

name
area
summary
projects
skills
education
interview_questions

### Displaying the Results

In [42]:
from IPython.display import display, Markdown 

def show_resume_result(result: dict): 
    """
    Displays the resume analysis results (dictionary) in a professional, 
    structured Markdown report format using all specified fields.
    """
    
    # --- Report Header ---
    candidate_name = result.get('name', 'Candidate Name Not Found')
    md = f"## 📄 Candidate Resume Analysis Report: {candidate_name}\n"
    md += f"--- \n"
    
    # --- Core Data ---
    md += f"### 1. Core Profile and Background\n"
    md += f"| **Candidate Name** | **{candidate_name}** |\n"
    md += f"| **Primary Area** | {result.get('area', 'N/A')} |\n"
    md += f"| **Education Summary** | {result.get('education', 'Not specified')} |\n"
    md += "\n"
    
    # --- Executive Summary ---
    md += f"### 2. Executive Summary\n"
    md += f"> {result.get('summary', 'Summary not extracted.')}\n\n"
    
    # --- Technical Skills ---
    md += f"### 3. Technical and Core Skills\n"
    skills = result.get('skills', [])
    if isinstance(skills, list) and skills:
        # Highlight each skill in bold
        md += f"**Key Skills:** {', '.join([f'**{s}**' for s in skills])}\n\n"
    else:
        md += "* Skills section was not clearly structured or is empty.\n\n"


    # ---  Project Achievements ---
    md += f"### 4. Project Achievements and Impact\n"
    projects = result.get('projects', [])
    
    if projects and isinstance(projects, list):
        for idx, project in enumerate(projects):
           
            title = project.get('project_title', f"Project {idx+1}")
            summary = project.get('achievements_summary', 'No achievement summary provided.')
            
            md += f"#### 4.{idx+1}. {title}\n"
            md += f"* **Summary of Achievement:** {summary}\n\n"
    else:
        md += "* Detailed project achievements or specific metrics were not found.\n\n"


    # --- Section 5: Interview Focus ---
    md += f"### Suggested Interview Question\n"
    md += f"💡 **Question:** {result.get('interview_questions', 'No specific question suggested.')}\n"
    
    # --- Display the Markdown Report ---
    display(Markdown(md))

In [43]:
show_resume_result(result_resume)

## 📄 Candidate Resume Analysis Report: KALEB SAXTON
---
### 1. Core Profile and Background
| **Candidate Name** | **KALEB SAXTON** |
| **Primary Area** | Data Science Management |
| **Education Summary** | B.S. in Mathematics and Economics from Rice University, Houston, TX (September 2008 - April 2012). |

### 2. Executive Summary
> Highly accomplished Data Science Manager with extensive experience in leading data science teams, developing predictive models, and driving significant business improvements. Proven track record in marketing mix modeling, conversion rate optimization, profit loss reduction, and enhancing operational efficiency through data-driven strategies and robust ETL infrastructure.

### 3. Technical and Core Skills
**Key Skills:** **Python (NumPy, Pandas, Scikitlearn, Keras, Flask)**, **SQL (Redshift, MySQL, Postgres, NoSQL)**, **Git**, **Leadership Experience**, **Recommendation Engines**, **Customer Segmentation**, **Propensity Modeling**, **Productionizing Models**, **Marketing Mix Models**, **Random Forest Models**, **ETL Infrastructure**, **Data Analysis**, **Reporting**

### 4. Project Achievements and Impact
#### 4.1. Marketing Mix Model Development (Westlake Chemical)
* **Summary of Achievement:** Supervised 3 data scientists and 1 data engineer in developing marketing mix models, leading to a 21% ROI improvement on digital marketing spend over 13 months.

#### 4.2. Client Conversion Rate Optimization (Westlake Chemical)
* **Summary of Achievement:** Collaborated with product and marketing teams to identify pre-client interactions increasing conversions, ultimately boosting conversion rates by 32%.

#### 4.3. Data Science Methodologies and Standards (Westlake Chemical)
* **Summary of Achievement:** Developed comprehensive documentation for methodologies and standards for the growing data science team.

#### 4.4. Project Duplication Reduction (Westlake Chemical)
* **Summary of Achievement:** Identified and reduced duplications across team projects by 92% through increased coordination and accountability.

#### 4.5. Production Prediction Engine (Energy Transfer Partners)
* **Summary of Achievement:** Worked closely with the product team to build a production prediction engine in Python, reducing crude oil profit loss by 16%.

#### 4.6. Well Subset Optimization (Energy Transfer Partners)
* **Summary of Achievement:** Used random forest models to study well subsets, optimizing and increasing efficiency by 22%.

#### 4.7. Automation and Profit Improvement (Energy Transfer Partners)
* **Summary of Achievement:** Recommended over 100 actionable steps within the first year, improving automation by 7% and profits by 9%.

#### 4.8. Process Improvement through Data Analysis (CenterPoint Energy)
* **Summary of Achievement:** Identified process improvements through client data analysis, leading to an 8% reduction in profit loss.

#### 4.9. Energy Production Reporting (CenterPoint Energy)
* **Summary of Achievement:** Owned reporting using Python and SQL for energy production, saving 30+ hours of manual work each week.

#### 4.10. ETL Infrastructure Development (CenterPoint Energy)
* **Summary of Achievement:** Built ETL infrastructures and delivered data to Redshift, increasing stakeholder decision-making output by 42%.

#### 4.11. Testing Strategies Development (CenterPoint Energy)
* **Summary of Achievement:** Created and developed 5 new testing strategies, along with creating and updating their documentation.

### Suggested Interview Question
💡 **Question:** Regarding your achievement at Westlake Chemical where you supervised the development of marketing mix models leading to a 21% ROI improvement, could you describe the most significant challenge your team faced during this project and how you navigated it?

### Creating the Description for the Job opening

In [44]:
job = {} 

job['title'] = "Senior Data Scientist (LLM Focus & Generative AI Research)"

job['description'] = """
YGT Tech is hiring a Senior Data Scientist specializing in Large Language Models (LLMs) to lead our Generative AI initiatives. This role requires a blend of advanced statistical analysis, machine learning expertise, and deep knowledge of NLP/NLG architectures (Transformers, RAG). You will be responsible for defining research agendas, designing experiments for human-like conversational models, and translating complex LLM outputs into measurable business insights and product features.
"""

job['details'] = """
Responsibilities:
- Design, implement, and evaluate custom LLM architectures and fine-tuning strategies (e.g., QLoRA, Reinforcement Learning with Human Feedback - RLHF).
- Lead research into Prompt Engineering methodologies and context window management to optimize model accuracy and faithfulness (grounding).
- Collaborate with MLOps and Engineering teams to transition successful LLM prototypes into scalable, production-ready APIs.
- Utilize classical Data Science techniques (statistics, causal inference) to analyze model performance, identify biases, and benchmark proprietary models against public APIs (e.g., OpenAI, Gemini).
- Develop and maintain comprehensive documentation detailing LLM architecture, training data curation, and ethical considerations.

Required Qualifications:
- 5+ years of experience in Data Science, with at least 2 years focused specifically on developing or integrating LLMs/Generative AI systems.
- Strong theoretical and practical understanding of Transformer models (BERT, GPT, Llama).
- Expert proficiency in Python (PyTorch/TensorFlow, Hugging Face ecosystem) and robust data manipulation skills (SQL, Pandas).
- Proven ability to manage full model lifecycle from exploratory research to production deployment.

Preferred Qualifications:
- Experience with vector databases and RAG (Retrieval-Augmented Generation) system design.
- Familiarity with data governance and privacy constraints specific to large-scale language data.
- Ph.D. in a quantitative field or published research in NLP/Generative Modeling.
"""

print(f"Job Title: {job['title']}")
print(f"\nJob Description: {job['description']}")
print(f"\nJob Details:\n{job['details']}")

Job Title: Senior Data Scientist (LLM Focus & Generative AI Research)

Job Description:
YGT Tech is hiring a Senior Data Scientist specializing in Large Language Models (LLMs) to lead our Generative AI initiatives. This role requires a blend of advanced statistical analysis, machine learning expertise, and deep knowledge of NLP/NLG architectures (Transformers, RAG). You will be responsible for defining research agendas, designing experiments for human-like conversational models, and translating complex LLM outputs into measurable business insights and product features.


Job Details:

Responsibilities:
- Design, implement, and evaluate custom LLM architectures and fine-tuning strategies (e.g., QLoRA, Reinforcement Learning with Human Feedback - RLHF).
- Lead research into Prompt Engineering methodologies and context window management to optimize model accuracy and faithfulness (grounding).
- Collaborate with MLOps and Engineering teams to transition successful LLM prototypes into scalable, production-ready APIs.
- Utilize classical Data Science techniques (statistics, causal inference) to analyze model performance, identify biases, and benchmark proprietary models against public APIs (e.g., OpenAI, Gemini).
- Develop and maintain comprehensive documentation detailing LLM architecture, training data curation, and ethical considerations.

Required Qualifications:
- 5+ years of experience in Data Science, with at least 2 years focused specifically on developing or integrating LLMs/Generative AI systems.
- Strong theoretical and practical understanding of Transformer models (BERT, GPT, Llama).
- Expert proficiency in Python (PyTorch/TensorFlow, Hugging Face ecosystem) and robust data manipulation skills (SQL, Pandas).
- Proven ability to manage full model lifecycle from exploratory research to production deployment.

Preferred Qualifications:
- Experience with vector databases and RAG (Retrieval-Augmented Generation) system design.
- Familiarity with data governance and privacy constraints specific to large-scale language data.
- Ph.D. in a quantitative field or published research in NLP/Generative Modeling.

### Saving Data to a CSV

In [45]:
import csv, os, pandas as pd

path_job_csv = "/Users/YGT/ygt/RAG-Resume-Analyzer-Agent/result/jobs.csv" 

def save_job_to_csv(data, filename): 
    headers = ['title', 'description', 'details'] 
    file_exists = os.path.exists(filename) 

    with open(filename, 'a', newline='', encoding='utf-8') as f: 
        writer = csv.DictWriter(f, fieldnames=headers, delimiter=';') 
        
        if not file_exists:
            writer.writeheader() 
        writer.writerow(data)

In [46]:
save_job_to_csv(job, path_job_csv)

In [47]:
df = pd.read_csv(path_job_csv, sep=";") 
df

,Senior Data Scientist (LLM Focus & Generative AI Research),"\nABC Tech is hiring a Senior Data Scientist specializing in Large Language Models (LLMs) to lead our Generative AI initiatives. This role requires a blend of advanced statistical analysis, machine learning expertise, and deep knowledge of NLP/NLG architectures (Transformers, RAG). You will be responsible for defining research agendas, designing experiments for human-like conversational models, and translating complex LLM outputs into measurable business insights and product features.\n","\n**Responsibilities:**\n- Design, implement, and evaluate custom LLM architectures and fine-tuning strategies (e.g., QLoRA, Reinforcement Learning with Human Feedback - RLHF).\n- Lead research into Prompt Engineering methodologies and context window management to optimize model accuracy and faithfulness (grounding).\n- Collaborate with MLOps and Engineering teams to transition successful LLM prototypes into scalable, production-ready APIs.\n- Utilize classical Data Science techniques (statistics, causal inference) to analyze model performance, identify biases, and benchmark proprietary models against public APIs (e.g., OpenAI, Gemini).\n- Develop and maintain comprehensive documentation detailing LLM architecture, training data curation, and ethical considerations.\n\n**Required Qualifications:**\n- 5+ years of experience in Data Science, with at least 2 years focused specifically on developing or integrating LLMs/Generative AI systems.\n- Strong theoretical and practical understanding of Transformer models (BERT, GPT, Llama).\n- Expert proficiency in Python (PyTorch/TensorFlow, Hugging Face ecosystem) and robust data manipulation skills (SQL, Pandas).\n- Proven ability to manage full model lifecycle from exploratory research to production deployment.\n\n**Preferred Qualifications:**\n- Experience with vector databases and RAG (Retrieval-Augmented Generation) system design.\n- Familiarity with data governance and privacy constraints specific to large-scale language data.\n- Ph.D. in a quantitative field or published research in NLP/Generative Modeling.\n"
0,Senior Data Scientist (LLM Focus & Generative ...,\nYGT Tech is hiring a Senior Data Scientist s...,"\nResponsibilities:\n- Design, implement, and ..."
1,Senior Data Scientist (LLM Focus & Generative ...,\nYGT Tech is hiring a Senior Data Scientist s...,"\nResponsibilities:\n- Design, implement, and ..."
2,Senior Data Scientist (LLM Focus & Generative ...,\nYGT Tech is hiring a Senior Data Scientist s...,"\nResponsibilities:\n- Design, implement, and ..."
3,Senior Data Scientist (LLM Focus & Generative ...,\nYGT Tech is hiring a Senior Data Scientist s...,"\nResponsibilities:\n- Design, implement, and ..."
4,Senior Data Scientist (LLM Focus & Generative ...,\nYGT Tech is hiring a Senior Data Scientist s...,"\nResponsibilities:\n- Design, implement, and ..."
5,Senior Data Scientist (LLM Focus & Generative ...,\nYGT Tech is hiring a Senior Data Scientist s...,"\nResponsibilities:\n- Design, implement, and ..."
6,Senior Data Scientist (LLM Focus & Generative ...,\nYGT Tech is hiring a Senior Data Scientist s...,"\nResponsibilities:\n- Design, implement, and ..."
7,Senior Data Scientist (LLM Focus & Generative ...,\nYGT Tech is hiring a Senior Data Scientist s...,"\nResponsibilities:\n- Design, implement, and ..."
8,Senior Data Scientist (LLM Focus & Generative ...,\nYGT Tech is hiring a Senior Data Scientist s...,"\nResponsibilities:\n- Design, implement, and ..."

In [48]:
def load_job(csv_file_path):

    with open(csv_file_path, "r", encoding="utf-8", errors="ignore") as f:
        raw_text = f.read().strip()

    if ";" in raw_text:
        parts = raw_text.split(";")
    else:
        parts = raw_text.split("\n\n")
        if len(parts) < 3:
            parts = raw_text.split("\n")
        if len(parts) < 3:
            parts = raw_text.split("  ")


    title = parts[0].strip()
    description = parts[1].strip()
    details = parts[2].strip()

    prompt_text = f"""
**Job Role for Analysis: {title}**

**Description:**  
{description}

**Full Requirements and Details:**  
{details}
"""
    return prompt_text.strip()

In [49]:
job_details = load_job(path_job_csv)   
job_details

'**Job Role for Analysis: Senior Data Scientist (LLM Focus & Generative AI Research)**\n\n**Description:**  \n"\nABC Tech is hiring a Senior Data Scientist specializing in Large Language Models (LLMs) to lead our Generative AI initiatives. This role requires a blend of advanced statistical analysis, machine learning expertise, and deep knowledge of NLP/NLG architectures (Transformers, RAG). You will be responsible for defining research agendas, designing experiments for human-like conversational models, and translating complex LLM outputs into measurable business insights and product features.\n"\n\n**Full Requirements and Details:**  \n"\n**Responsibilities:**\n- Design, implement, and evaluate custom LLM architectures and fine-tuning strategies (e.g., QLoRA, Reinforcement Learning with Human Feedback - RLHF).\n- Lead research into Prompt Engineering methodologies and context window management to optimize model accuracy and faithfulness (grounding).\n- Collaborate with MLOps and Engineering teams to transition successful LLM prototypes into scalable, production-ready APIs.\n- Utilize classical Data Science techniques (statistics, causal inference) to analyze model performance, identify biases, and benchmark proprietary models against public APIs (e.g., OpenAI, Gemini).\n- Develop and maintain comprehensive documentation detailing LLM architecture, training data curation, and ethical considerations.\n\n**Required Qualifications:**\n- 5+ years of experience in Data Science, with at least 2 years focused specifically on developing or integrating LLMs/Generative AI systems.\n- Strong theoretical and practical understanding of Transformer models (BERT, GPT, Llama).\n- Expert proficiency in Python (PyTorch/TensorFlow, Hugging Face ecosystem) and robust data manipulation skills (SQL, Pandas).\n- Proven ability to manage full model lifecycle from exploratory research to production deployment.\n\n**Preferred Qualifications:**\n- Experience with vector databases and RAG (Retrieval-Augmented Generation) system design.\n- Familiarity with data governance and privacy constraints specific to large-scale language data.\n- Ph.D. in a quantitative field or published research in NLP/Generative Modeling.\n"\nSenior Data Scientist (LLM Focus & Generative AI Research)'

### Customizing Prompt and Chain

In [50]:
prompt_template = ChatPromptTemplate.from_template(
"""
You are a Human Resources specialist with extensive experience in resume analysis. 
Your task is to review the content below and extract the information using the exact JSON structure provided.
Respond with only the structured JSON output and use only the specified keys. 
Make sure the key names match the schema exactly. 
Do not include explanations or comments outside the JSON.

Schema:
{schema}
                                                   
--- 

Resume to be analyzed: 
'{resume}'   

---

Job description: 
'{job}'

""")

In [51]:
prompt_template

ChatPromptTemplate(input_variables=['job', 'resume', 'schema'], input_types={}, partial_variables={}, messages=[HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['job', 'resume', 'schema'], input_types={}, partial_variables={}, template="\nYou are a Human Resources specialist with extensive experience in resume analysis. \nYour task is to review the content below and extract the information using the exact JSON structure provided.\nRespond with only the structured JSON output and use only the specified keys. \nMake sure the key names match the schema exactly. \nDo not include explanations or comments outside the JSON.\n\nSchema:\n{schema}\n\n--- \n\nResume to be analyzed: \n'{resume}'   \n\n---\n\nJob description: \n'{job}'\n\n"), additional_kwargs={})])

In [52]:
def process_resume(schema, content, job_details, prompt_template, llm): 
    chain = prompt_template | llm 
    output = chain.invoke({"schema": schema, "resume": content, "job":job_details}) 
    result = format_result(output.content) 
    return output, result

In [53]:
structured_data = parse_result_llm(output, fields) 
save_json_resume(structured_data, path_json) 
result_resume = load_json_resume("/Users/YGT/ygt/RAG-Resume-Analyzer-Agent/result/resumes.json")
show_resume_result(result_resume)

## 📄 Candidate Resume Analysis Report: KALEB SAXTON
---
### 1. Core Profile and Background
| **Candidate Name** | **KALEB SAXTON** |
| **Primary Area** | Data Science Management |
| **Education Summary** | B.S. in Mathematics and Economics from Rice University, Houston, TX (September 2008 - April 2012). |

### 2. Executive Summary
> Highly accomplished Data Science Manager with extensive experience in leading data science teams, developing predictive models, and driving significant business improvements. Proven track record in marketing mix modeling, conversion rate optimization, profit loss reduction, and enhancing operational efficiency through data-driven strategies and robust ETL infrastructure.

### 3. Technical and Core Skills
**Key Skills:** **Python (NumPy, Pandas, Scikitlearn, Keras, Flask)**, **SQL (Redshift, MySQL, Postgres, NoSQL)**, **Git**, **Leadership Experience**, **Recommendation Engines**, **Customer Segmentation**, **Propensity Modeling**, **Productionizing Models**, **Marketing Mix Models**, **Random Forest Models**, **ETL Infrastructure**, **Data Analysis**, **Reporting**

### 4. Project Achievements and Impact
#### 4.1. Marketing Mix Model Development (Westlake Chemical)
* **Summary of Achievement:** Supervised 3 data scientists and 1 data engineer in developing marketing mix models, leading to a 21% ROI improvement on digital marketing spend over 13 months.

#### 4.2. Client Conversion Rate Optimization (Westlake Chemical)
* **Summary of Achievement:** Collaborated with product and marketing teams to identify pre-client interactions increasing conversions, ultimately boosting conversion rates by 32%.

#### 4.3. Data Science Methodologies and Standards (Westlake Chemical)
* **Summary of Achievement:** Developed comprehensive documentation for methodologies and standards for the growing data science team.

#### 4.4. Project Duplication Reduction (Westlake Chemical)
* **Summary of Achievement:** Identified and reduced duplications across team projects by 92% through increased coordination and accountability.

#### 4.5. Production Prediction Engine (Energy Transfer Partners)
* **Summary of Achievement:** Worked closely with the product team to build a production prediction engine in Python, reducing crude oil profit loss by 16%.

#### 4.6. Well Subset Optimization (Energy Transfer Partners)
* **Summary of Achievement:** Used random forest models to study well subsets, optimizing and increasing efficiency by 22%.

#### 4.7. Automation and Profit Improvement (Energy Transfer Partners)
* **Summary of Achievement:** Recommended over 100 actionable steps within the first year, improving automation by 7% and profits by 9%.

#### 4.8. Process Improvement through Data Analysis (CenterPoint Energy)
* **Summary of Achievement:** Identified process improvements through client data analysis, leading to an 8% reduction in profit loss.

#### 4.9. Energy Production Reporting (CenterPoint Energy)
* **Summary of Achievement:** Owned reporting using Python and SQL for energy production, saving 30+ hours of manual work each week.

#### 4.10. ETL Infrastructure Development (CenterPoint Energy)
* **Summary of Achievement:** Built ETL infrastructures and delivered data to Redshift, increasing stakeholder decision-making output by 42%.

#### 4.11. Testing Strategies Development (CenterPoint Energy)
* **Summary of Achievement:** Created and developed 5 new testing strategies, along with creating and updating their documentation.

### Suggested Interview Question
💡 **Question:** Regarding your achievement at Westlake Chemical where you supervised the development of marketing mix models leading to a 21% ROI improvement, could you describe the most significant challenge your team faced during this project and how you navigated it?

### Deeper Analysis

In [54]:
schema = """
{ 
    "name": "Full name of the candidate", 
    "area": "Primary area of field", 
    "summary": "Concise summary of the candidate",
    "projects": [
        {"project_title": "string", "achievements_summary": "string"},
        {"project_title": "string", "achievements_summary": "string"}
    ],
    "skills": ["skill 1", "skill 2", "..."],
    "education": "Summary of the most relevant academic background", 
    "interview_questions": "Useful interview question based on the resume, to clarify or explore a specific point",
    "strengths": ["Key strengths that suggest alignment with the desired role, such as relevant experience or valuable skills"], 
    "areas_for_development": ["Points that indicate potential gaps or risks, like missing experience or unlisted technologies"], 
    "important_considerations":["Specific notes that require extra attention or verification, as as missing key information"], 
    "final_recommendation": "Final summary with suggestion of next steps (e.g., proceed to interview, request clarification, or consider for a different role)"
}
"""

In [55]:
fields = ["name",
    "area",
    "summary",
    "projects",
    "skills",
    "education",
    "interview_questions", 
    "strengths", 
    "areas_for_development", 
    "important_considerations", 
    "final_recommendation"
    ]

In [56]:
output, result = process_resume(schema, content, job_details, prompt_template, llm)

In [57]:
structured_data = parse_result_llm(output, fields) 
save_json_resume(structured_data, path_json) 
result_resume = load_json_resume(path_json) 
structured_data

{'name': 'KALEB SAXTON',
 'area': 'Data Science, Machine Learning, and Analytics Management',
 'summary': 'Kaleb Saxton is an experienced Data Science Manager with over 10 years in data science and analytics roles, including Senior Data Scientist and Data Analyst. He possesses strong skills in Python (NumPy, Pandas, Scikit-learn, Keras, Flask), SQL (Redshift, MySQL, Postgres, NoSQL), Git, and leadership. His expertise includes developing and productionizing models, customer segmentation, recommendation engines, and driving significant ROI and efficiency improvements across various industries.',
 'projects': [{'project_title': 'Marketing Mix Model Development & Conversion Rate Optimization',
   'achievements_summary': 'Supervised a team of data scientists and engineers to develop marketing mix models, resulting in a 21% ROI improvement on digital marketing spend. Collaborated with product and marketing teams to identify pre-client interactions, increasing conversion rates by 32%.'},
  {'project_title': 'Data Science Team Standards & Efficiency',
   'achievements_summary': 'Developed documentation for methodologies and standards for the growing data science team. Identified and reduced project duplications by 92% through increased coordination and accountability.'},
  {'project_title': 'Production Prediction Engine for Crude Oil Profit Loss Reduction',
   'achievements_summary': 'Worked closely with the product team to build a production prediction engine in Python, which reduced crude oil profit loss by 16%. Used random forest models to optimize well subsets, increasing efficiency by 22%.'},
  {'project_title': 'Stakeholder Reporting & Automation Improvements',
   'achievements_summary': 'Compiled and prepared data and reports for stakeholders and functional teams. Recommended over 100 actionable steps within the first year that improved automation by 7% and profits by 9%.'},
  {'project_title': 'Client Data Analysis & ETL Infrastructure Development',
   'achievements_summary': 'Identified process improvements through client data analysis, leading to an 8% reduction in profit loss. Owned reporting using Python and SQL for energy production, saving 30+ hours of manual work each week. Built ETL infrastructures and delivered data to Redshift, increasing stakeholder decision-making output by 42%.'}],
 'skills': ['Python (NumPy, Pandas, Scikit-learn, Keras, Flask)',
  'SQL (Redshift, MySQL, Postgres, NoSQL)',
  'Git',
  'Leadership Experience',
  'Recommendation Engines',
  'Customer Segmentation',
  'Propensity Modeling',
  'Productionizing Models',
  'ETL Infrastructures',
  'Data Analysis',
  'Random Forest Models',
  'Marketing Mix Models'],
 'education': 'B.S. in Mathematics and Economics from Rice University (September 2008 - April 2012).',
 'interview_questions': "Your resume demonstrates strong general data science and leadership experience. Could you elaborate on any projects or self-study initiatives you've undertaken that specifically involve Large Language Models (LLMs), Generative AI, Transformer architectures, or related technologies like PyTorch/TensorFlow, Hugging Face, RAG, or Prompt Engineering?",
 'strengths': ['Extensive Data Science Experience: Over 10 years in data science roles, exceeding the 5+ years requirement.',
  'Strong Python and SQL Proficiency: Expert in Python (NumPy, Pandas, Keras, Flask) and various SQL databases, aligning with core technical requirements.',
  'Full Model Lifecycle Management: Proven ability to build and productionize models, a key responsibility for the role.',
  'Leadership and Team Management: Experience as a Data Science Manager, supervising teams and developing methodologies.',
  'Impactful Problem Solving: Demonstrated ability to drive measurable business outcomes (ROI improvement, conversion rate increase, profit loss reduction, efficiency gains).',
  'Data Analysis and Reporting: Strong background in analyzing data, identifying improvements, and preparing reports for stakeholders.',
  'ETL Experience: Experience building ETL infrastructures, which is valuable for data pipelines supporting LLMs.'],
 'areas_for_development': ['LLM/Generative AI Specific Experience: Lacks explicit mention of 2+ years focused on developing or integrating LLMs/Generative AI systems.',
  'Transformer Model Knowledge: No explicit mention of theoretical or practical understanding of Transformer models (BERT, GPT, Llama).',
  'Specific ML Frameworks: While Python is strong, PyTorch/TensorFlow and Hugging Face ecosystem are not explicitly listed.',
  'Advanced LLM Techniques: No mention of custom LLM architectures, fine-tuning strategies (QLoRA, RLHF), Prompt Engineering, or context window management.',
  'Vector Databases/RAG: No experience listed with vector databases or Retrieval-Augmented Generation (RAG) system design.',
  'Academic Background: Holds a B.S. rather than a Ph.D. or published research in NLP/Generative Modeling, which is a preferred qualification.',
  'Data Governance/Privacy: No explicit mention of familiarity with data governance and privacy constraints specific to large-scale language data.'],
 'important_considerations': ["The candidate's resume is highly relevant for a general Senior Data Scientist role, but the target job has a very specific and deep focus on LLMs and Generative AI, which is not explicitly covered in the resume.",
  'While the candidate has strong foundational skills, the lack of explicit LLM-specific experience is a significant gap that needs to be addressed.',
  "The candidate's leadership experience as a Data Science Manager could be an asset if they can demonstrate the required technical depth in LLMs."],
 'final_recommendation': 'Request clarification. Kaleb possesses strong foundational data science skills, leadership experience, and a proven track record of delivering business value. However, the resume does not explicitly demonstrate the specialized LLM and Generative AI expertise required for this specific Senior Data Scientist role. An initial screening call or a targeted interview would be necessary to assess his direct experience, theoretical knowledge, and passion for LLMs and Generative AI, and to determine if his transferable skills and learning agility can bridge the identified gaps.'}

In [58]:
def show_resume_result(result: dict): 
    """
    Displays the resume analysis results (dictionary) in a professional, 
    structured Markdown report format using all specified fields, 
    including new analysis fields (Strengths, Gaps, Recommendations).
    """
    
    # --- Report Header ---
    candidate_name = result.get('name', 'Candidate Name Not Found')
    md = f"## 📄 Candidate Resume Analysis Report: {candidate_name}\n"
    md += f"--- \n"
    
    # --- 1. Core Data ---
    md += f"### 1. Core Profile and Background\n"
    md += f"| Criterion | Value |\n"
    md += f"| :--- | :--- |\n"
    md += f"| **Candidate Name** | **{candidate_name}** |\n"
    md += f"| **Primary Area** | {result.get('area', 'N/A')} |\n"
    md += f"| **Education Summary** | {result.get('education', 'Not specified')} |\n"
    md += "\n"
    
    # --- 2. Executive Summary ---
    md += f"### 2. Executive Summary\n"
    md += f"> {result.get('summary', 'Summary not extracted.')}\n\n"
    
    # --- 3. Technical Skills ---
    md += f"### 3. Technical and Core Skills\n"
    skills = result.get('skills', [])
    if isinstance(skills, list) and skills:
        md += f"**Key Skills:** {', '.join([f'**{s}**' for s in skills])}\n\n"
    else:
        md += "* Skills section was not clearly structured or is empty.\n\n"


    # --- 4. Project Achievements ---
    md += f"### 4. Project Achievements and Impact\n"
    projects = result.get('projects', [])
    
    if projects and isinstance(projects, list):
        for idx, project in enumerate(projects):
            title = project.get('project_title', f"Project {idx+1}")
            summary = project.get('achievements_summary', 'No achievement summary provided.')
            
            md += f"#### 4.{idx+1}. {title}\n"
            md += f"* **Achievement Summary:** {summary}\n\n"
    else:
        md += "* Detailed project achievements or specific metrics were not found.\n\n"

    
    # --- 5. Alignment and Development Analysis (NEW SECTION) ---
    md += f"### 5. Fit & Development Analysis\n"
    
    # Strengths
    md += f"#### 5.1. Core Strengths\n"
    strengths = result.get('strengths', [])
    if isinstance(strengths, list) and strengths:
        for item in strengths:
            md += f"* **✅ {item}**\n"
    else:
        md += "* No specific strengths listed.\n"

    # Areas for Development (Gaps)
    md += f"#### 5.2. Areas for Development (Gaps/Risks)\n"
    areas_for_development = result.get('areas_for_development', [])
    if isinstance(areas_for_development, list) and areas_for_development:
        for item in areas_for_development:
            md += f"* **❌ {item}**\n"
    else:
        md += "* No immediate development areas identified.\n"
        
    # Important Considerations
    md += f"#### 5.3. Important Considerations\n"
    important_considerations = result.get('important_considerations', [])
    if isinstance(important_considerations, list) and important_considerations:
        for item in important_considerations:
            md += f"* ⚠️ {item}\n"
    else:
        md += "* No specific notes or verification required.\n"
    md += "\n"


    # --- 6. Interview Focus and Final Recommendation ---
    
    # Interview Question
    md += f"### 6. Next Steps\n"
    md += f"#### Suggested Interview Question\n"
    md += f"💡 **Question:** {result.get('interview_questions', 'No specific question suggested.')}\n\n"
    
    # Final Recommendation
    md += f"#### Final Hiring Recommendation\n"
    md += f"**Overall Fit:** **{result.get('final_recommendation', 'Assessment Missing').upper()}**\n"
    md += f"*(Recommendation is based on fit against the provided Job Description.)*\n"

    
    # --- Display the Markdown Report ---
    display(Markdown(md))

In [59]:
show_resume_result(structured_data )

## 📄 Candidate Resume Analysis Report: KALEB SAXTON
---
### 1. Core Profile and Background
| Criterion | Value |
| :--- | :--- |
| **Candidate Name** | **KALEB SAXTON** |
| **Primary Area** | Data Science, Machine Learning, and Analytics Management |
| **Education Summary** | B.S. in Mathematics and Economics from Rice University (September 2008 - April 2012). |

### 2. Executive Summary
> Kaleb Saxton is an experienced Data Science Manager with over 10 years in data science and analytics roles, including Senior Data Scientist and Data Analyst. He possesses strong skills in Python (NumPy, Pandas, Scikit-learn, Keras, Flask), SQL (Redshift, MySQL, Postgres, NoSQL), Git, and leadership. His expertise includes developing and productionizing models, customer segmentation, recommendation engines, and driving significant ROI and efficiency improvements across various industries.

### 3. Technical and Core Skills
**Key Skills:** **Python (NumPy, Pandas, Scikit-learn, Keras, Flask)**, **SQL (Redshift, MySQL, Postgres, NoSQL)**, **Git**, **Leadership Experience**, **Recommendation Engines**, **Customer Segmentation**, **Propensity Modeling**, **Productionizing Models**, **ETL Infrastructures**, **Data Analysis**, **Random Forest Models**, **Marketing Mix Models**

### 4. Project Achievements and Impact
#### 4.1. Marketing Mix Model Development & Conversion Rate Optimization
* **Achievement Summary:** Supervised a team of data scientists and engineers to develop marketing mix models, resulting in a 21% ROI improvement on digital marketing spend. Collaborated with product and marketing teams to identify pre-client interactions, increasing conversion rates by 32%.

#### 4.2. Data Science Team Standards & Efficiency
* **Achievement Summary:** Developed documentation for methodologies and standards for the growing data science team. Identified and reduced project duplications by 92% through increased coordination and accountability.

#### 4.3. Production Prediction Engine for Crude Oil Profit Loss Reduction
* **Achievement Summary:** Worked closely with the product team to build a production prediction engine in Python, which reduced crude oil profit loss by 16%. Used random forest models to optimize well subsets, increasing efficiency by 22%.

#### 4.4. Stakeholder Reporting & Automation Improvements
* **Achievement Summary:** Compiled and prepared data and reports for stakeholders and functional teams. Recommended over 100 actionable steps within the first year that improved automation by 7% and profits by 9%.

#### 4.5. Client Data Analysis & ETL Infrastructure Development
* **Achievement Summary:** Identified process improvements through client data analysis, leading to an 8% reduction in profit loss. Owned reporting using Python and SQL for energy production, saving 30+ hours of manual work each week. Built ETL infrastructures and delivered data to Redshift, increasing stakeholder decision-making output by 42%.

### 5. Fit & Development Analysis
#### 5.1. Core Strengths
* **✅ Extensive Data Science Experience: Over 10 years in data science roles, exceeding the 5+ years requirement.**
* **✅ Strong Python and SQL Proficiency: Expert in Python (NumPy, Pandas, Keras, Flask) and various SQL databases, aligning with core technical requirements.**
* **✅ Full Model Lifecycle Management: Proven ability to build and productionize models, a key responsibility for the role.**
* **✅ Leadership and Team Management: Experience as a Data Science Manager, supervising teams and developing methodologies.**
* **✅ Impactful Problem Solving: Demonstrated ability to drive measurable business outcomes (ROI improvement, conversion rate increase, profit loss reduction, efficiency gains).**
* **✅ Data Analysis and Reporting: Strong background in analyzing data, identifying improvements, and preparing reports for stakeholders.**
* **✅ ETL Experience: Experience building ETL infrastructures, which is valuable for data pipelines supporting LLMs.**
#### 5.2. Areas for Development (Gaps/Risks)
* **❌ LLM/Generative AI Specific Experience: Lacks explicit mention of 2+ years focused on developing or integrating LLMs/Generative AI systems.**
* **❌ Transformer Model Knowledge: No explicit mention of theoretical or practical understanding of Transformer models (BERT, GPT, Llama).**
* **❌ Specific ML Frameworks: While Python is strong, PyTorch/TensorFlow and Hugging Face ecosystem are not explicitly listed.**
* **❌ Advanced LLM Techniques: No mention of custom LLM architectures, fine-tuning strategies (QLoRA, RLHF), Prompt Engineering, or context window management.**
* **❌ Vector Databases/RAG: No experience listed with vector databases or Retrieval-Augmented Generation (RAG) system design.**
* **❌ Academic Background: Holds a B.S. rather than a Ph.D. or published research in NLP/Generative Modeling, which is a preferred qualification.**
* **❌ Data Governance/Privacy: No explicit mention of familiarity with data governance and privacy constraints specific to large-scale language data.**
#### 5.3. Important Considerations
* ⚠️ The candidate's resume is highly relevant for a general Senior Data Scientist role, but the target job has a very specific and deep focus on LLMs and Generative AI, which is not explicitly covered in the resume.
* ⚠️ While the candidate has strong foundational skills, the lack of explicit LLM-specific experience is a significant gap that needs to be addressed.
* ⚠️ The candidate's leadership experience as a Data Science Manager could be an asset if they can demonstrate the required technical depth in LLMs.

### 6. Next Steps
#### Suggested Interview Question
💡 **Question:** Your resume demonstrates strong general data science and leadership experience. Could you elaborate on any projects or self-study initiatives you've undertaken that specifically involve Large Language Models (LLMs), Generative AI, Transformer architectures, or related technologies like PyTorch/TensorFlow, Hugging Face, RAG, or Prompt Engineering?

#### Final Hiring Recommendation
**Overall Fit:** **REQUEST CLARIFICATION. KALEB POSSESSES STRONG FOUNDATIONAL DATA SCIENCE SKILLS, LEADERSHIP EXPERIENCE, AND A PROVEN TRACK RECORD OF DELIVERING BUSINESS VALUE. HOWEVER, THE RESUME DOES NOT EXPLICITLY DEMONSTRATE THE SPECIALIZED LLM AND GENERATIVE AI EXPERTISE REQUIRED FOR THIS SPECIFIC SENIOR DATA SCIENTIST ROLE. AN INITIAL SCREENING CALL OR A TARGETED INTERVIEW WOULD BE NECESSARY TO ASSESS HIS DIRECT EXPERIENCE, THEORETICAL KNOWLEDGE, AND PASSION FOR LLMS AND GENERATIVE AI, AND TO DETERMINE IF HIS TRANSFERABLE SKILLS AND LEARNING AGILITY CAN BRIDGE THE IDENTIFIED GAPS.**
*(Recommendation is based on fit against the provided Job Description.)*

### Calculating a Match Score

In [60]:
prompt_score = """
Based on the specific job opening, calculate a final score from 0.0 to 10.0.
The output for this field must include only the final score (x.x), with no additional text or comments.
Be fair and rigorous in your evaluation. A perfect score of 10.0 should only be assigned to candidates who clearly exceed all expectations for the role.

Evaluation criteria:
1. Experience (Weight: 35%) – Analyze previous roles, total time of experience, and how closely they match the job responsibilities.
2. Technical Skills (Weight: 25%) – Check how well the candidate's technical skills align with the job requirements.
3. Education (Weight: 15%) – Assess the relevance of degrees or certifications for the position, including institutions and years of study.
4. Strengths (Weight: 15%) – Evaluate how well the candidate's strengths support the role.
5. Weaknesses (Penalty up to 10%) – Consider the severity of any weaknesses or misalignments with the job requirements.
"""

In [61]:
prompt_template = ChatPromptTemplate.from_template("""
You are a Human Resources specialist with extensive experience in resume analysis.
Your task is to review the content below and extract the information using the exact JSON structure provided.
Respond with only the structured JSON output and use only the specified keys.
Make sure the key names match the schema exactly.
Do not include explanations or comments outside the JSON.

Schema:
{schema}

---

Rules for calculate the score:
{prompt_score}

---

Resume to be analyzed:
'{resume}'

---

Job description:
'{job}'

""")
prompt_template

ChatPromptTemplate(input_variables=['job', 'prompt_score', 'resume', 'schema'], input_types={}, partial_variables={}, messages=[HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['job', 'prompt_score', 'resume', 'schema'], input_types={}, partial_variables={}, template="\nYou are a Human Resources specialist with extensive experience in resume analysis.\nYour task is to review the content below and extract the information using the exact JSON structure provided.\nRespond with only the structured JSON output and use only the specified keys.\nMake sure the key names match the schema exactly.\nDo not include explanations or comments outside the JSON.\n\nSchema:\n{schema}\n\n---\n\nRules for calculate the score:\n{prompt_score}\n\n---\n\nResume to be analyzed:\n'{resume}'\n\n---\n\nJob description:\n'{job}'\n\n"), additional_kwargs={})])

In [62]:
schema = """
{
  "name": "Full name of the candidate",
  "area": "Primary area or field. Classify in only one of these: IT, Marketing, Sales, Financial, Administrative, Others. ",
  "summary": "Concise summary of the candidate",
  "skills": ["skill 1", "skill 2", "..."],
  "education": "Summary of the most relevant academic background",
  "interview_questions": ["At least 3 useful interview question based on the resume, to clarify or explore a specific point"],
  "strengths": ["Key strengths that suggest alignment with the desired role, such as relevant experience or valuable skills"],
  "areas_for_development": ["Points that indicate potential gaps or risks, like missing experience or unlisted technologies"],
  "important_considerations": ["Specific notes that require extra attention or verification, such as missing key information"],
  "final_recommendations": "Final summary with suggestion of next steps (e.g., proceed to interview, request clarification, or consider for a different role)"
  "score": 0.0
}
"""

fields = [
    "name",
    "area",
    "summary",
    "skills",
    "education",
    "interview_questions",
    "strengths",
    "areas_for_development",
    "important_considerations",
    "final_recommendations",
    "score"
]

# Conclusion and Final Function

Parameters:
- schema: expected data structure for the result
- job_details: job opening information
- prompt_template: LangChain prompt template
- prompt_score: additional instruction to guide resume scoring
- llm: instance of the language model (via LangChain)

Returns:
- output: raw response from the LLM
- result: formatted response based on the schema

In [63]:
def parse_doc(file_path):
  converter = DocumentConverter()
  result = converter.convert(file_path)
  content = result.document.export_to_markdown()
  return content

In [77]:
def process_resume(schema, job_details, prompt_template, prompt_score, llm, file_path):

  if file_path:
    if not os.path.exists(file_path):
      raise FileNotFoundError(f"File not found: {file_path}")

  content = parse_doc(file_path)

  chain = prompt_template | llm
  output = chain.invoke({"schema": schema, "resume": content, "job": job_details, "prompt_score": prompt_score})

  result= (output.content)

  return output, result

In [80]:
file_cv = "/Users/YGT/ygt/RAG-Resume-Analyzer-Agent/documents/data-science-manager-resume-example.pdf"
output, result = process_resume(schema, job_details, prompt_template, prompt_score, llm, file_cv)
try:
    structured_data = format_result(result) 
except Exception as e:
    structured_data = parse_result_llm(output, fields)
structured_data

2025-11-17 20:04:27,437 - INFO - detected formats: [<InputFormat.PDF: 'pdf'>]
2025-11-17 20:04:27,438 - INFO - Going to convert document batch...
2025-11-17 20:04:27,439 - INFO - Initializing pipeline for StandardPdfPipeline with options hash 4f2edc0f7d9bb60b38ebfecf9a2609f5
2025-11-17 20:04:27,439 - INFO - Auto OCR model selected ocrmac.
2025-11-17 20:04:27,439 - INFO - Accelerator device: 'mps'
2025-11-17 20:04:29,527 - INFO - Accelerator device: 'mps'
2025-11-17 20:04:30,124 - INFO - Processing document data-science-manager-resume-example.pdf
2025-11-17 20:04:31,045 - INFO - Finished converting document data-science-manager-resume-example.pdf in 3.61 sec.

{'name': 'Kaleb Saxton',
 'area': 'IT',
 'summary': 'Kaleb Saxton is an experienced Data Science Manager with over a decade of experience in data analysis, predictive modeling, and leading data science initiatives. He has a strong background in Python (NumPy, Pandas, Scikit-learn, Keras) and SQL, with a proven track record of delivering significant business improvements through marketing mix models, conversion rate optimization, and productionizing data solutions.',
 'skills': ['Python (NumPy, Pandas, Scikitlearn, Keras, Flask)',
  'SQL (Redshift, MySQL, Postgres, NoSQL)',
  'Git',
  'Leadership Experience',
  'Recommendation Engines',
  'Customer Segmentation',
  'Propensity Modeling',
  'Productionizing Models'],
 'education': 'B.S. in Mathematics and Economics from Rice University (September 2008 - April 2012).',
 'interview_questions': ["The job description emphasizes LLMs and Generative AI. Can you describe any projects or experiences you've had with Large Language Models, Transformer architectures, or related NLP/NLG techniques?",
  "The role requires proficiency in PyTorch/TensorFlow and the Hugging Face ecosystem. While you've listed Keras, can you elaborate on your experience with these specific frameworks and tools for deep learning and NLP?",
  'Given your current role as a Data Science Manager, how do you envision transitioning to a Senior Data Scientist role that is highly focused on hands-on research and development in Generative AI?'],
 'strengths': ['Extensive experience (11+ years) in data science and analytics, including leadership roles.',
  'Proven ability to drive measurable business impact and ROI through data-driven insights and models.',
  'Strong proficiency in core data science tools like Python (Pandas, Scikit-learn) and SQL.',
  'Experience in productionizing models and building data infrastructure (ETL).',
  'Solid academic foundation in Mathematics and Economics from a reputable university.'],
 'areas_for_development': ['Lack of explicit experience or skills related to Large Language Models (LLMs), Generative AI, Transformer architectures (BERT, GPT, Llama), or NLP/NLG.',
  'No mention of key LLM-specific frameworks and tools such as PyTorch, TensorFlow (beyond Keras), Hugging Face ecosystem, vector databases, or RAG.',
  'No indication of experience with advanced LLM techniques like QLoRA, RLHF, or Prompt Engineering.',
  'Does not meet the preferred qualification of a Ph.D. or published research in NLP/Generative Modeling.'],
 'important_considerations': ["The candidate's resume is strong for a traditional Senior Data Scientist or Data Science Manager role, but it does not align with the highly specialized LLM/Generative AI focus of this specific job opening.",
  'The transition from a Data Science Manager to a hands-on Senior Data Scientist role, especially in a new, highly specialized domain, would need careful evaluation.',
  'Significant upskilling in LLM-specific technologies and concepts would likely be required for this candidate to succeed in the role.'],
 'final_recommendations': 'While Kaleb Saxton possesses a strong general data science background and a proven track record of delivering business value, his resume lacks the specific and extensive experience required for a Senior Data Scientist role with an LLM Focus & Generative AI Research. Recommend not proceeding with an interview for this specific role due to a fundamental mismatch in core technical expertise. However, the candidate could be a strong fit for other, more traditional data science or analytics roles within the organization.',
 'score': 1.9}

In [81]:
with open(path_json, "w", encoding="utf-8") as f:
    json.dump([], f, ensure_ascii=False, indent=2)

# Saving as Json

In [82]:
def save_json_cv(new_data, path_json, key_name="name"):
  if os.path.exists(path_json):
    with open(path_json, "r", encoding="utf-8") as f:
      data = json.load(f)
  else:
    data = []

  if isinstance(data, dict):
    data = [data]

  candidates = [entry.get(key_name) for entry in data]
  if new_data.get(key_name) in candidates:
    print(f"Resume '{new_data.get(key_name)}' already registered. Ignoring it.")
    return

  data.append(new_data)
  with open(path_json, "w", encoding="utf-8") as f:
    json.dump(data, f, indent=2, ensure_ascii=False)

In [83]:
save_json_cv(structured_data, path_json)

In [84]:
def display_json_table(path_json):
  with open(path_json, "r", encoding="utf-8") as f:
    data = json.load(f)
  df = pd.json_normalize(data)
  return df

In [85]:
df = display_json_table(path_json)
display(df)

,name,area,summary,skills,education,interview_questions,strengths,areas_for_development,important_considerations,final_recommendations,score
0,Kaleb Saxton,IT,Kaleb Saxton is an experienced Data Science Ma...,"[Python (NumPy, Pandas, Scikitlearn, Keras, Fl...",B.S. in Mathematics and Economics from Rice Un...,[The job description emphasizes LLMs and Gener...,[Extensive experience (11+ years) in data scie...,[Lack of explicit experience or skills related...,[The candidate's resume is strong for a tradit...,While Kaleb Saxton possesses a strong general ...,1.9

In [89]:
path = "/Users/YGT/ygt/RAG-Resume-Analyzer-Agent/documents/data-scientist-resume-example.pdf"
output, result = process_resume(schema, job_details, prompt_template, prompt_score, llm, path)
try:
    structured_data = format_result(result) 
except Exception as e:
    structured_data = parse_result_llm(output, fields)
    
save_json_cv(structured_data, path_json)

df = display_json_table(path_json)
display(df)

2025-11-17 20:19:29,637 - INFO - detected formats: [<InputFormat.PDF: 'pdf'>]
2025-11-17 20:19:29,639 - INFO - Going to convert document batch...
2025-11-17 20:19:29,640 - INFO - Initializing pipeline for StandardPdfPipeline with options hash 4f2edc0f7d9bb60b38ebfecf9a2609f5
2025-11-17 20:19:29,640 - INFO - Auto OCR model selected ocrmac.
2025-11-17 20:19:29,641 - INFO - Accelerator device: 'mps'
2025-11-17 20:19:31,928 - INFO - Accelerator device: 'mps'
2025-11-17 20:19:32,536 - INFO - Processing document data-scientist-resume-example.pdf
2025-11-17 20:19:33,391 - INFO - Finished converting document data-scientist-resume-example.pdf in 3.76 sec.

,name,area,summary,skills,education,interview_questions,strengths,areas_for_development,important_considerations,final_recommendations,score
0,Kaleb Saxton,IT,Kaleb Saxton is an experienced Data Science Ma...,"[Python (NumPy, Pandas, Scikitlearn, Keras, Fl...",B.S. in Mathematics and Economics from Rice Un...,[The job description emphasizes LLMs and Gener...,[Extensive experience (11+ years) in data scie...,[Lack of explicit experience or skills related...,[The candidate's resume is strong for a tradit...,While Kaleb Saxton possesses a strong general ...,1.9
1,Kandace Loudor,IT,Highly experienced Data Scientist with over 9 ...,"[Python (NumPy, Pandas, Scikit-learn, Keras, F...","B.S. in Statistics from Rutgers University, co...",[The Senior Data Scientist role at ABC Tech is...,[Extensive experience (9+ years) in data scien...,[Lack of explicit experience with Large Langua...,[The candidate possesses strong general data s...,While Kandace has an impressive general data s...,3.5

In [90]:
df[["name", "score", "summary"]]

             name  score                                            summary
0    Kaleb Saxton    1.9  Kaleb Saxton is an experienced Data Science Ma...
1  Kandace Loudor    3.5  Highly experienced Data Scientist with over 9 ...

In [91]:
!pip install -q streamlit python-dotenv
!npm install -q localtunnel
!pip install pyngrok -q

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

zsh:1: command not found: npm

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

# Final Code

In [ ]:
def load_llm(id_model: str, temperature: float): 
    llm = ChatGoogleGenerativeAI(
        model="gemini-2.5-flash",
        temperature=temperature,
        max_tokens=None,
        timeout=None,
        max_retries=2
    )
    
    return llm 

from langchain_ollama import ChatOllama

def load_local_llm(): 
    llm = ChatOllama( 
        model="llama3", 
        temperature=0
    ) 

    return llm 

def clean_llm_response(response, return_thinking=False):
  response = response.strip()

  if return_thinking:
    response = response.replace("<think>", "[thinking...] ")
    response = response.replace("</think>", "\n---\n")

  else:
    if "</think>" in res:
      response = response.split("</think>")[-1].strip()

  return response 

def parse_document_to_markdown(file_path):
  converter = DocumentConverter()
  result = converter.convert(file_path)
  content = result.document.export_to_markdown()
  return content

def extract_structured_json(response_text: str, required_fields: list) -> dict:
        #  Remove the reasoning part (<think>...</think>)
        if "</think>" in response_text:
            response_text = response_text.split("</think>")[-1].strip()

        # Locates JSON and parses it
        start_idx = response_text.find('{')
        end_idx = response_text.rfind('}') + 1
        if start_idx == -1 or end_idx == 0:
            raise json.JSONDecodeError("No JSON found in response", response_text, 0)

        json_str = response_text[start_idx:end_idx]
        info_cv = json.loads(json_str)

        for field in required_fields:
            if field not in info_cv:
                info_cv[field] = []

        return info_cv

In [93]:
def save_json_cv(new_data, path_json, key_name="name"):
    """
    Appends new resume data (new_data) to an existing JSON file, 
    preventing duplicate entries based on the key_name (default is "name").
    """
    
    if os.path.exists(path_json):
        try:
            with open(path_json, "r", encoding="utf-8") as f:
                data = json.load(f)
        except json.JSONDecodeError:
            # If the file is empty or corrupted, start with an empty list.
            data = []
        
    else:
        # If the file does not exist, start with an empty list.
        data = []

    # Ensure data is a list, even if the file only contained a single dictionary.
    if isinstance(data, dict):
        data = [data]
    
    # Check for duplicates
    # Filter out non-dictionary entries just in case of file corruption.
    candidates = [entry.get(key_name) for entry in data if isinstance(entry, dict)]
    
    candidate_id = new_data.get(key_name)
    
    if candidate_id in candidates:
        # Replaced st.warning with standard Python print, optionally using color for emphasis.
        print(f"WARNING: Resume '{candidate_id}' already registered. Ignoring addition.")
        return

    # Add new data and save
    data.append(new_data)
    with open(path_json, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)

In [94]:
def load_json_cv(path_json):
    with open(path_json, "r", encoding="utf-8") as f:
        return json.load(f)

In [95]:
def show_cv_result(result: dict): 
    """
    Displays the resume analysis results (dictionary) in a professional, 
    structured Markdown report format using all specified fields, 
    including new analysis fields (Strengths, Gaps, Recommendations).
    """
    
    # --- Report Header ---
    candidate_name = result.get('name', 'Candidate Name Not Found')
    md = f"## 📄 Candidate Resume Analysis Report: {candidate_name}\n"
    md += f"--- \n"
    
    # --- 1. Core Data ---
    md += f"### 1. Core Profile and Background\n"
    md += f"| Criterion | Value |\n"
    md += f"| :--- | :--- |\n"
    md += f"| **Candidate Name** | **{candidate_name}** |\n"
    md += f"| **Primary Area** | {result.get('area', 'N/A')} |\n"
    md += f"| **Education Summary** | {result.get('education', 'Not specified')} |\n"
    md += "\n"
    
    # --- 2. Executive Summary ---
    md += f"### 2. Executive Summary\n"
    md += f"> {result.get('summary', 'Summary not extracted.')}\n\n"
    
    # --- 3. Technical Skills ---
    md += f"### 3. Technical and Core Skills\n"
    skills = result.get('skills', [])
    if isinstance(skills, list) and skills:
        md += f"**Key Skills:** {', '.join([f'**{s}**' for s in skills])}\n\n"
    else:
        md += "* Skills section was not clearly structured or is empty.\n\n"


    # --- 4. Project Achievements ---
    md += f"### 4. Project Achievements and Impact\n"
    projects = result.get('projects', [])
    
    if projects and isinstance(projects, list):
        for idx, project in enumerate(projects):
            title = project.get('project_title', f"Project {idx+1}")
            summary = project.get('achievements_summary', 'No achievement summary provided.')
            
            md += f"#### 4.{idx+1}. {title}\n"
            md += f"* **Achievement Summary:** {summary}\n\n"
    else:
        md += "* Detailed project achievements or specific metrics were not found.\n\n"

    
    # ---  Alignment and Development Analysis  ---
    md += f"### 5. Fit & Development Analysis\n"
    
    # Strengths
    md += f"#### 5.1. Core Strengths\n"
    strengths = result.get('strengths', [])
    if isinstance(strengths, list) and strengths:
        for item in strengths:
            md += f"* **✅ {item}**\n"
    else:
        md += "* No specific strengths listed.\n"

    # Areas for Development (Gaps)
    md += f"#### 5.2. Areas for Development (Gaps/Risks)\n"
    areas_for_development = result.get('areas_for_development', [])
    if isinstance(areas_for_development, list) and areas_for_development:
        for item in areas_for_development:
            md += f"* **❌ {item}**\n"
    else:
        md += "* No immediate development areas identified.\n"
        
    # Important Considerations
    md += f"#### 5.3. Important Considerations\n"
    important_considerations = result.get('important_considerations', [])
    if isinstance(important_considerations, list) and important_considerations:
        for item in important_considerations:
            md += f"* ⚠️ {item}\n"
    else:
        md += "* No specific notes or verification required.\n"
    md += "\n"


    # --- Interview Focus and Final Recommendation ---
    
    # Interview Question
    md += f"### 6. Next Steps\n"
    md += f"#### Suggested Interview Question\n"
    md += f"💡 **Question:** {result.get('interview_questions', 'No specific question suggested.')}\n\n"
    
    # Final Recommendation
    md += f"#### Final Hiring Recommendation\n"
    md += f"**Overall Fit:** **{result.get('final_recommendation', 'Assessment Missing').upper()}**\n"
    md += f"*(Recommendation is based on fit against the provided Job Description.)*\n"

    
    # --- Display the Markdown Report ---
    display(Markdown(md))

In [96]:
def save_job_to_csv(data, filename):
    headers = ['title', 'description', 'details']
    file_exists = os.path.exists(filename)

    with open(filename, 'a', newline='', encoding='utf-8') as f:
        writer = csv.DictWriter(f, fieldnames=headers, delimiter=';')
        if not file_exists:
            writer.writeheader()
        writer.writerow(data)

In [104]:
def load_job(csv_path):
  try:
    # sep=';' ve encoding='utf-8' ile dosyayı oku
    df = pd.read_csv(csv_path, sep=';', encoding='utf-8')
    
    if 'title' not in df.columns:
        raise ValueError(f"Title not found.")
        
    job = df.iloc[-1]
    
    prompt_text = f"""
    **Job for {job['title']}**

    **Description:**
    {job['description']}

    **Full Details:**
    {job['details']}
    """

    return prompt_text.strip()

  except FileNotFoundError:
    return "Error: Job file not found"
  except (ValueError, IndexError, KeyError) as e:
    return f"Error: CSV data could not be parsed. Please delete the file and try again. Detail: {e}"

In [98]:
def format_result(result):
    cleaned_string = result.strip()
    
    if cleaned_string.startswith("'") and cleaned_string.endswith("'"):
        cleaned_string = cleaned_string[1:-1].strip()
    
    match = re.search(r'\{.*\}', cleaned_string, re.DOTALL)
    
    if match:
        final_json_string = match.group(0)
    else:
        final_json_string = cleaned_string

    return json.loads(final_json_string)

In [147]:
def process_cv(schema, job_details, prompt_template, prompt_score, llm, file_path):

  if file_path:
    if not os.path.exists(file_path):
      raise FileNotFoundError(f"File not found: {file_path}")

  content = parse_doc(file_path)

  chain = prompt_template | llm
  output = chain.invoke({"schema": schema, "resume": content, "job": job_details, "prompt_score": prompt_score})
  raw_response_text = output.content
  result = format_result(raw_response_text)

  return output, result

In [148]:
def display_json_table(path_json):
  with open(path_json, "r", encoding="utf-8") as f:
    data = json.load(f)

  df = pd.DataFrame(data)
  return df

In [149]:
cv_file_path = "/Users/YGT/ygt/RAG-Resume-Analyzer-Agent/documents/data-science-manager-resume-example.pdf" # Elinizdeki CV yolu
job_csv_path = "/Users/YGT/ygt/RAG-Resume-Analyzer-Agent/result/jobs.csv"

In [150]:
job_details_text = load_job(job_csv_path)

In [151]:
llm = load_local_llm()

In [158]:
def json_repair(raw_text):
    text = raw_text.strip()

    if text.startswith("{") and not text.endswith("}"):
        text += "}"

    return text.strip()

In [ ]:
def process_cv_raw(schema, job_details, prompt_template, prompt_score, llm, file_path):

    content = parse_doc(file_path) 
    chain = prompt_template | llm
    output = chain.invoke({"schema": schema, "resume": content, "job": job_details, "prompt_score": prompt_score})
    response = output.content
    return output, response 

output_message, raw_json_text = process_cv_raw(
    schema, 
    job_details_text, 
    prompt_template, 
    prompt_score, 
    llm, 
    cv_file_path
)

2025-11-18 16:05:30,029 - INFO - detected formats: [<InputFormat.PDF: 'pdf'>]
2025-11-18 16:05:30,032 - INFO - Going to convert document batch...
2025-11-18 16:05:30,032 - INFO - Initializing pipeline for StandardPdfPipeline with options hash 4f2edc0f7d9bb60b38ebfecf9a2609f5
2025-11-18 16:05:30,034 - INFO - Auto OCR model selected ocrmac.
2025-11-18 16:05:30,035 - INFO - Accelerator device: 'mps'
2025-11-18 16:05:32,239 - INFO - Accelerator device: 'mps'
2025-11-18 16:05:32,908 - INFO - Processing document data-science-manager-resume-example.pdf
2025-11-18 16:05:34,025 - INFO - Finished converting document data-science-manager-resume-example.pdf in 4.00 sec.
2025-11-18 16:05:36,966 - INFO - HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

{
  "name": "Kaleb Saxton",
  "area": "IT",
  "summary": "Data Science Manager with experience in developing marketing mix models, identifying duplications across team projects, and optimizing efficiency.",
  "skills": ["Python", "NumPy", "Pandas", "Scikitlearn", "Keras", "Flask", "SQL", "Redshift", "MySQL", "Postgres", "NoSQL", "Git"],
  "education": "B.S. in Mathematics and Economics from Rice University (September 2008 - April 2012)",
  "interview_questions": ["Can you elaborate on your experience with recommendation engines?", "How do you approach identifying duplications across team projects?", "Can you walk me through a time when you optimized efficiency?"],
  "strengths": ["Leadership Experience", "Recommendation Engines", "Customer Segmentation", "Propensity Modeling", "Productionizing Models"],
  "areas_for_development": ["Missing key information on job description"],
  "important_considerations": [],
  "final_recommendations": "Proceed to interview",
  "score": 8.5

In [159]:

json_text = json_repair(raw_json_text)

In [163]:
structured_data = format_result(json_text)
structured_data

{'name': 'Kaleb Saxton',
 'area': 'IT',
 'summary': 'Data Science Manager with experience in developing marketing mix models, identifying duplications across team projects, and optimizing efficiency.',
 'skills': ['Python',
  'NumPy',
  'Pandas',
  'Scikitlearn',
  'Keras',
  'Flask',
  'SQL',
  'Redshift',
  'MySQL',
  'Postgres',
  'NoSQL',
  'Git'],
 'education': 'B.S. in Mathematics and Economics from Rice University (September 2008 - April 2012)',
 'interview_questions': ['Can you elaborate on your experience with recommendation engines?',
  'How do you approach identifying duplications across team projects?',
  'Can you walk me through a time when you optimized efficiency?'],
 'strengths': ['Leadership Experience',
  'Recommendation Engines',
  'Customer Segmentation',
  'Propensity Modeling',
  'Productionizing Models'],
 'areas_for_development': ['Missing key information on job description'],
 'important_considerations': [],
 'final_recommendations': 'Proceed to interview',
 'score': 8.5}

In [167]:
path_json = "/Users/YGT/ygt/RAG-Resume-Analyzer-Agent/result/resumes.json"
save_json_cv(structured_data, path_json, key_name="name")
result_resume_list = load_json_cv(path_json)
if result_resume_list:
    last_resume = result_resume_list[-1]

    print(last_resume)

WARNING: Resume 'Kaleb Saxton' already registered. Ignoring addition.
{'name': 'Kandace Loudor', 'area': 'IT', 'summary': 'Highly experienced Data Scientist with over 9 years of experience in deploying recommendation engines, time series forecasting, customer attrition modeling, and leading data science teams. Proven ability to translate complex data into business insights and drive significant improvements in key metrics across various industries.', 'skills': ['Python (NumPy, Pandas, Scikit-learn, Keras, Flask)', 'SQL (MySQL, Postgres)', 'Git', 'AWS', 'Time Series Forecasting', 'Productionizing Models', 'Recommendation Engines', 'Customer Segmentation'], 'education': 'B.S. in Statistics from Rutgers University, completed September 2011 - April 2015.', 'interview_questions': ["The Senior Data Scientist role at ABC Tech is heavily focused on Large Language Models (LLMs) and Generative AI. While your resume demonstrates strong general data science skills, there isn't explicit mention of LLM-specific experience. Can you describe any projects or self-study you've undertaken related to LLMs, Transformers, or NLP/NLG architectures?", 'The role requires proficiency with frameworks like PyTorch/TensorFlow and the Hugging Face ecosystem. Your experience lists Keras. Can you elaborate on your experience with other deep learning frameworks, particularly those used for large-scale NLP, and how quickly you adapt to new technologies?', 'You have excellent experience in deploying models to production. Can you walk us through your understanding of the unique challenges and considerations when transitioning LLM prototypes into scalable, production-ready APIs, especially regarding prompt engineering, context window management, and grounding?'], 'strengths': ['Extensive experience (9+ years) in data science, including leadership roles and mentoring junior data scientists.', 'Proven track record of deploying models to production and achieving quantifiable business impact (e.g., increased order size, improved retention, cost savings).', 'Strong foundational data science skills, including recommendation engines, time series forecasting, and customer segmentation.', 'Experience in collaborating with product and marketing teams to translate business needs into data solutions.', 'Proficiency in Python, SQL, and cloud platforms (AWS).'], 'areas_for_development': ['Lack of explicit experience with Large Language Models (LLMs), Generative AI, or advanced NLP/NLG architectures (Transformers, RAG).', 'No mention of specific LLM-related frameworks or libraries such as PyTorch, TensorFlow (beyond Keras), or the Hugging Face ecosystem.', 'Missing experience with vector databases, which are often crucial for RAG systems.', 'No indication of research or academic background in NLP/Generative Modeling (Ph.D. or publications are preferred for this specialized role).'], 'important_considerations': ["The candidate possesses strong general data science skills and experience, but the core specialization required for this 'LLM Focus & Generative AI Research' role appears to be missing.", "It is crucial to ascertain the candidate's interest, foundational knowledge, and willingness to rapidly acquire expertise in LLMs and Generative AI during an interview.", 'While Keras is a deep learning framework, its application to large-scale NLP/LLMs is not explicitly detailed, and other key frameworks are absent.'], 'final_recommendations': 'While Kandace has an impressive general data science background with significant achievements, there is a substantial gap in the specific LLM and Generative AI expertise required for this specialized Senior Data Scientist role. It is recommended to proceed with an initial screening call to assess her foundational understanding of LLMs, her passion for the domain, and her capacity for rapid upskilling. If she demonstrates strong potential and enthusiasm for this specific area, a technical interview could follow to delve deeper into her problem-solving approach and learning agility. Otherwise, she might be a better fit for a general Senior Data Scientist role without the LLM specialization.', 'score': 3.5}

In [168]:
last_resume

{'name': 'Kandace Loudor',
 'area': 'IT',
 'summary': 'Highly experienced Data Scientist with over 9 years of experience in deploying recommendation engines, time series forecasting, customer attrition modeling, and leading data science teams. Proven ability to translate complex data into business insights and drive significant improvements in key metrics across various industries.',
 'skills': ['Python (NumPy, Pandas, Scikit-learn, Keras, Flask)',
  'SQL (MySQL, Postgres)',
  'Git',
  'AWS',
  'Time Series Forecasting',
  'Productionizing Models',
  'Recommendation Engines',
  'Customer Segmentation'],
 'education': 'B.S. in Statistics from Rutgers University, completed September 2011 - April 2015.',
 'interview_questions': ["The Senior Data Scientist role at ABC Tech is heavily focused on Large Language Models (LLMs) and Generative AI. While your resume demonstrates strong general data science skills, there isn't explicit mention of LLM-specific experience. Can you describe any projects or self-study you've undertaken related to LLMs, Transformers, or NLP/NLG architectures?",
  'The role requires proficiency with frameworks like PyTorch/TensorFlow and the Hugging Face ecosystem. Your experience lists Keras. Can you elaborate on your experience with other deep learning frameworks, particularly those used for large-scale NLP, and how quickly you adapt to new technologies?',
  'You have excellent experience in deploying models to production. Can you walk us through your understanding of the unique challenges and considerations when transitioning LLM prototypes into scalable, production-ready APIs, especially regarding prompt engineering, context window management, and grounding?'],
 'strengths': ['Extensive experience (9+ years) in data science, including leadership roles and mentoring junior data scientists.',
  'Proven track record of deploying models to production and achieving quantifiable business impact (e.g., increased order size, improved retention, cost savings).',
  'Strong foundational data science skills, including recommendation engines, time series forecasting, and customer segmentation.',
  'Experience in collaborating with product and marketing teams to translate business needs into data solutions.',
  'Proficiency in Python, SQL, and cloud platforms (AWS).'],
 'areas_for_development': ['Lack of explicit experience with Large Language Models (LLMs), Generative AI, or advanced NLP/NLG architectures (Transformers, RAG).',
  'No mention of specific LLM-related frameworks or libraries such as PyTorch, TensorFlow (beyond Keras), or the Hugging Face ecosystem.',
  'Missing experience with vector databases, which are often crucial for RAG systems.',
  'No indication of research or academic background in NLP/Generative Modeling (Ph.D. or publications are preferred for this specialized role).'],
 'important_considerations': ["The candidate possesses strong general data science skills and experience, but the core specialization required for this 'LLM Focus & Generative AI Research' role appears to be missing.",
  "It is crucial to ascertain the candidate's interest, foundational knowledge, and willingness to rapidly acquire expertise in LLMs and Generative AI during an interview.",
  'While Keras is a deep learning framework, its application to large-scale NLP/LLMs is not explicitly detailed, and other key frameworks are absent.'],
 'final_recommendations': 'While Kandace has an impressive general data science background with significant achievements, there is a substantial gap in the specific LLM and Generative AI expertise required for this specialized Senior Data Scientist role. It is recommended to proceed with an initial screening call to assess her foundational understanding of LLMs, her passion for the domain, and her capacity for rapid upskilling. If she demonstrates strong potential and enthusiasm for this specific area, a technical interview could follow to delve deeper into her problem-solving approach and learning agility. Otherwise, she might be a better fit for a general Senior Data Scientist role without the LLM specialization.',
 'score': 3.5}